import { ConstructionTemplate } from './constructionTemplates';

// ===== SHARED CATEGORY BUILDERS =====
// ราคาอ้างอิงจากตลาดจริง 2024-2025

function designCategory(isOptional = false) {
  return {
    no: 'A',
    description: 'ค่าออกแบบ / แบบก่อสร้าง',
    isOptional,
    items: [
      {
        no: 'A.1',
        description: 'ค่าออกแบบสถาปัตยกรรม + Interior',
        unit: 'ตร.ม.',
        unitPrice: 600,
        laborCost: 0,
        scopeDetails: '- แบบ Layout Plan\n- แบบ Interior / Exterior Design\n- 3D Perspective ทุกห้อง',
        quantityMode: { type: 'area-multiplier' as const, factor: 1 },
      },
      {
        no: 'A.2',
        description: 'ค่าแบบโครงสร้าง (Structural Drawing)',
        unit: 'ตร.ม.',
        unitPrice: 250,
        laborCost: 0,
        scopeDetails: '- แบบฐานราก/เสาเข็ม\n- แบบเสา/คาน/พื้น\n- แบบโครงหลังคา\n- คำนวณโครงสร้าง',
        quantityMode: { type: 'area-multiplier' as const, factor: 1 },
      },
      {
        no: 'A.3',
        description: 'ค่าแบบระบบ MEP (ไฟฟ้า/ประปา/แอร์)',
        unit: 'ตร.ม.',
        unitPrice: 150,
        laborCost: 0,
        scopeDetails: '- แบบระบบไฟฟ้า (Single Line Diagram)\n- แบบระบบประปา/สุขาภิบาล\n- แบบระบบปรับอากาศ',
        quantityMode: { type: 'area-multiplier' as const, factor: 1 },
      },
    ],
  };
}

function vanavardInteriorDesignCategory() {
  return {
    no: 'A',
    description: 'ค่าออกแบบ Interior + BOQ',
    items: [
      {
        no: 'A.1',
        description: 'ค่าออกแบบภายใน พร้อมแบบก่อสร้างและ BOQ',
        unit: 'ตร.ม.',
        unitPrice: 1000,
        laborCost: 0,
        scopeDetails: '- Layout Plan / Furniture Plan\n- Mood & Material Direction\n- 3D Perspective\n- Elevation / Section Drawing\n- Built-in Detail + BOQ',
        quantityMode: { type: 'area-multiplier' as const, factor: 1 },
      },
    ],
  };
}

function demolitionCategory(forHouse = false) {
  return {
    no: 'B',
    description: 'งานรื้อถอน / เตรียมพื้นที่',
    items: forHouse
      ? [
          {
            no: 'B.1',
            description: 'งานเคลียร์พื้นที่ / ถางหญ้า / ต้นไม้',
            unit: 'ตร.ม.',
            unitPrice: 30,
            laborCost: 50,
            scopeDetails: '- ถางหญ้า/ตัดต้นไม้\n- เคลียร์เศษวัสดุ\n- ปรับพื้นที่ให้เรียบ',
            quantityMode: { type: 'area-multiplier' as const, factor: 1 },
          },
          {
            no: 'B.2',
            description: 'งานปรับระดับดิน / ถมดิน',
            unit: 'คิว',
            unitPrice: 350,
            laborCost: 150,
            scopeDetails: '- ดินถมบดอัด\n- ปรับระดับตามแบบ\n- บดอัดทุก 30 ซม.',
            quantityMode: { type: 'area-multiplier' as const, factor: 0.3 },
          },
          {
            no: 'B.3',
            description: 'งานรื้อถอนสิ่งปลูกสร้างเดิม (ถ้ามี)',
            unit: 'เหมา',
            unitPrice: 15000,
            laborCost: 20000,
            scopeDetails: '- รื้อถอนอาคาร/ส่วนต่อเติมเดิม\n- ขนย้ายเศษวัสดุ\n- ทำความสะอาดพื้นที่',
            quantityMode: { type: 'fixed' as const, value: 1 },
            isOptional: true,
          },
        ]
      : [
          {
            no: 'B.1',
            description: 'รื้อถอนฝ้าเพดานเดิม',
            unit: 'ตร.ม.',
            unitPrice: 50,
            laborCost: 80,
            scopeDetails: '- รื้อฝ้ายิปซั่ม/แคลเซียมซิลิเกตเดิม\n- รื้อโครงฝ้า\n- ขนย้ายเศษวัสดุ',
            quantityMode: { type: 'area-multiplier' as const, factor: 0.8 },
          },
          {
            no: 'B.2',
            description: 'รื้อถอนพื้นเดิม (กระเบื้อง/ไม้/พรม)',
            unit: 'ตร.ม.',
            unitPrice: 30,
            laborCost: 100,
            scopeDetails: '- รื้อกระเบื้อง/ลามิเนต/พรมเดิม\n- ขัดกาวเก่า\n- ปรับระดับ',
            quantityMode: { type: 'area-multiplier' as const, factor: 0.7 },
          },
          {
            no: 'B.3',
            description: 'รื้อถอนผนังกั้นห้อง / ประตู-หน้าต่างเดิม',
            unit: 'เหมา',
            unitPrice: 8000,
            laborCost: 12000,
            scopeDetails: '- รื้อผนังยิปซั่ม/อิฐเดิม\n- รื้อวงกบ/ประตู/หน้าต่าง\n- เก็บทำความสะอาด',
            quantityMode: { type: 'fixed' as const, value: 1 },
          },
          {
            no: 'B.4',
            description: 'รื้อถอนงานระบบเดิม (ไฟฟ้า/ประปา)',
            unit: 'เหมา',
            unitPrice: 5000,
            laborCost: 8000,
            scopeDetails: '- ถอดสายไฟ/ท่อเดิม\n- ถอดสุขภัณฑ์เดิม\n- ปิดจุดต่อ ปลอดภัย',
            quantityMode: { type: 'fixed' as const, value: 1 },
          },
          {
            no: 'B.5',
            description: 'ขนย้ายเศษวัสดุ + ค่าทิ้ง',
            unit: 'เที่ยว',
            unitPrice: 3500,
            laborCost: 1500,
            scopeDetails: '- รถบรรทุก 6 ล้อ\n- ขนเศษวัสดุไปทิ้ง\n- ค่าทิ้งที่ลานทิ้ง',
            quantityMode: { type: 'fixed' as const, value: 3 },
          },
        ],
  };
}

function masonryCategory() {
  return {
    no: 'C',
    description: 'งานก่อฉาบ / ผนัง',
    items: [
      {
        no: 'C.1',
        description: 'ก่อผนังอิฐมวลเบา หนา 7.5 ซม.',
        unit: 'ตร.ม.',
        unitPrice: 120,
        laborCost: 350,
        scopeDetails: '- อิฐมวลเบา Q-CON / Super Block 7.5 ซม.\n- ปูนก่ออิฐมวลเบา\n- ใช้สำหรับผนังกั้นห้อง',
        quantityMode: { type: 'perimeter' as const, wallHeight: 2.0 },
      },
      {
        no: 'C.2',
        description: 'ก่อผนังอิฐมวลเบา หนา 10 ซม.',
        unit: 'ตร.ม.',
        unitPrice: 150,
        laborCost: 400,
        scopeDetails: '- อิฐมวลเบา Q-CON / Super Block 10 ซม.\n- ปูนก่ออิฐมวลเบา\n- ใช้สำหรับผนังภายนอก/ผนังรับน้ำหนัก',
        quantityMode: { type: 'perimeter' as const, wallHeight: 1.0 },
      },
      {
        no: 'C.3',
        description: 'ฉาบปูนผนัง 2 ด้าน',
        unit: 'ตร.ม.',
        unitPrice: 40,
        laborCost: 300,
        scopeDetails: '- ปูนฉาบสำเร็จรูป (ตราเสือ/จระเข้)\n- ฉาบหนา 1-1.5 ซม.\n- ตีเส้นระดับ/ฉาบเรียบ',
        quantityMode: { type: 'perimeter' as const, wallHeight: 2.8 },
      },
      {
        no: 'C.4',
        description: 'เสาเอ็น / คานทับหลัง คสล.',
        unit: 'เมตร',
        unitPrice: 250,
        laborCost: 450,
        scopeDetails: '- เหล็ก DB12 4 เส้น + ปลอก RB6 @15 ซม.\n- คอนกรีต 240 ksc\n- ไม้แบบ\n- ใช้เสริมผนังก่อ',
        quantityMode: { type: 'perimeter' as const, wallHeight: 0.5 },
      },
      {
        no: 'C.5',
        description: 'วงกบประตู-หน้าต่าง + ทับหลัง',
        unit: 'ช่อง',
        unitPrice: 800,
        laborCost: 600,
        scopeDetails: '- วงกบเหล็กชุบ/อลูมิเนียม\n- คานทับหลังเหนือช่อง\n- เก็บขอบ/ยาแนว',
        quantityMode: { type: 'per-room' as const, defaultCount: 6 },
      },
    ],
  };
}

function electricalCategory() {
  return {
    no: 'D',
    description: 'งานระบบไฟฟ้า',
    items: [
      {
        no: 'D.1',
        description: 'ตู้ Consumer Unit (MDB) + Main Breaker',
        unit: 'ตู้',
        unitPrice: 4500,
        laborCost: 2500,
        scopeDetails: '- ตู้โหลดเซ็นเตอร์ 12-18 ช่อง (Schneider/Haco)\n- Main Breaker 50-63A\n- กราวด์บาร์/นิวทรัลบาร์\n- ติดตั้งพร้อมเดินสาย',
        quantityMode: { type: 'fixed' as const, value: 1 },
      },
      {
        no: 'D.2',
        description: 'เบรกเกอร์ MCB 16-20A (วงจรไฟ/ปลั๊ก)',
        unit: 'ตัว',
        unitPrice: 280,
        laborCost: 150,
        scopeDetails: '- MCB 1P 16-20A (Schneider/ABB)\n- 1 วงจรต่อ 1 ห้อง/โซน\n- ติดตั้งในตู้ Consumer Unit',
        quantityMode: { type: 'per-room' as const, defaultCount: 6 },
      },
      {
        no: 'D.3',
        description: 'เบรกเกอร์ MCB 32A (วงจรหนัก แอร์/เตา/เครื่องทำน้ำอุ่น)',
        unit: 'ตัว',
        unitPrice: 450,
        laborCost: 200,
        scopeDetails: '- MCB 2P 32A สำหรับวงจรหนัก\n- แยกวงจรแอร์แต่ละเครื่อง\n- วงจรเตาไฟฟ้า/เครื่องทำน้ำอุ่น',
        quantityMode: { type: 'per-room' as const, defaultCount: 4 },
      },
      {
        no: 'D.4',
        description: 'RCBO / ELCB กันไฟดูด 30mA',
        unit: 'ตัว',
        unitPrice: 1200,
        laborCost: 300,
        scopeDetails: '- RCBO 30mA (Schneider/ABB)\n- ป้องกันไฟรั่ว/ไฟดูด\n- ติดตั้งวงจรห้องน้ำ/ภายนอก',
        quantityMode: { type: 'fixed' as const, value: 2 },
      },
      {
        no: 'D.5',
        description: 'สายไฟ THW 1.5 sq.mm. (วงจรไฟฟ้าแสงสว่าง)',
        unit: 'เมตร',
        unitPrice: 7,
        laborCost: 15,
        scopeDetails: '- สาย THW 1.5 sq.mm. (Phelps Dodge/BCC)\n- ใช้เดินวงจรไฟฟ้าแสงสว่าง\n- สีตามมาตรฐาน (แดง/ดำ/เขียว)',
        quantityMode: { type: 'per-point' as const, pointsPerSqm: 3 },
      },
      {
        no: 'D.6',
        description: 'สายไฟ THW 2.5 sq.mm. (วงจรปลั๊ก)',
        unit: 'เมตร',
        unitPrice: 11,
        laborCost: 15,
        scopeDetails: '- สาย THW 2.5 sq.mm. (Phelps Dodge/BCC)\n- ใช้เดินวงจรปลั๊กไฟ\n- สีตามมาตรฐาน',
        quantityMode: { type: 'per-point' as const, pointsPerSqm: 2.5 },
      },
      {
        no: 'D.7',
        description: 'สายไฟ THW/VCT 4-6 sq.mm. (วงจรหนัก)',
        unit: 'เมตร',
        unitPrice: 25,
        laborCost: 20,
        scopeDetails: '- สาย THW 4 sq.mm. / VCT 2x4 sq.mm.\n- สำหรับแอร์/เตาไฟฟ้า/เครื่องทำน้ำอุ่น\n- เดินแยกวงจร',
        quantityMode: { type: 'per-point' as const, pointsPerSqm: 0.8 },
      },
      {
        no: 'D.8',
        description: 'ท่อร้อยสาย PVC 3/8" + 1/2"',
        unit: 'เมตร',
        unitPrice: 12,
        laborCost: 18,
        scopeDetails: '- ท่อ PVC สีขาว 3/8" (ไฟ) / 1/2" (ปลั๊ก)\n- ข้อต่อ/ข้องอ/คลิปรัด\n- เฟล็กซ์ (Flexible Conduit)',
        quantityMode: { type: 'per-point' as const, pointsPerSqm: 3 },
      },
      {
        no: 'D.9',
        description: 'จุดปลั๊กไฟ 3 ขา (Panasonic Wide Series)',
        unit: 'จุด',
        unitPrice: 180,
        laborCost: 250,
        scopeDetails: '- ปลั๊ก 3 ขา Panasonic Wide Series\n- บ็อกซ์ฝัง 4×4"\n- หน้ากาก + ฝาครอบ\n- รวมเดินสาย + ติดตั้ง',
        quantityMode: { type: 'per-point' as const, pointsPerSqm: 0.5 },
      },
      {
        no: 'D.10',
        description: 'สวิตช์ไฟ 1-3 Gang (Panasonic Wide Series)',
        unit: 'จุด',
        unitPrice: 200,
        laborCost: 250,
        scopeDetails: '- สวิตช์ 1/2/3 Gang Panasonic Wide Series\n- บ็อกซ์ฝัง 4×4"\n- หน้ากาก + ฝาครอบ\n- รวมเดินสาย + ติดตั้ง',
        quantityMode: { type: 'per-point' as const, pointsPerSqm: 0.3 },
      },
      {
        no: 'D.11',
        description: 'ดาวน์ไลท์ LED 7-9W (Warm White)',
        unit: 'ดวง',
        unitPrice: 250,
        laborCost: 150,
        scopeDetails: '- ดาวน์ไลท์ LED 7-9W ฝังฝ้า\n- ขนาด 3.5-4 นิ้ว\n- Warm White 3000K\n- อายุใช้งาน 30,000 ชม.',
        quantityMode: { type: 'per-point' as const, pointsPerSqm: 0.4 },
      },
      {
        no: 'D.12',
        description: 'ดาวน์ไลท์ LED 12-15W (ห้องใหญ่/ห้องครัว)',
        unit: 'ดวง',
        unitPrice: 380,
        laborCost: 150,
        scopeDetails: '- ดาวน์ไลท์ LED 12-15W ฝังฝ้า\n- ขนาด 5-6 นิ้ว\n- Daylight 6500K / Warm White 3000K\n- สำหรับห้องที่ต้องการแสงมาก',
        quantityMode: { type: 'per-point' as const, pointsPerSqm: 0.15 },
      },
      {
        no: 'D.13',
        description: 'ไฟเส้น LED Strip (ซ่อนฝ้า/ร่องไฟ)',
        unit: 'เมตร',
        unitPrice: 120,
        laborCost: 80,
        scopeDetails: '- LED Strip 2835/5050\n- 12V/24V + Adapter\n- Warm White 3000K\n- อลูมิเนียม Profile (ถ้ามี)',
        quantityMode: { type: 'per-point' as const, pointsPerSqm: 0.3 },
        isOptional: true,
      },
      {
        no: 'D.14',
        description: 'สายกราวด์ + หลักดิน (Grounding)',
        unit: 'ชุด',
        unitPrice: 2500,
        laborCost: 1500,
        scopeDetails: '- สาย THW 10 sq.mm. สีเขียว\n- หลักดิน Copper Rod 5/8"×2.4 ม.\n- แคล้มป์/ข้อต่อ\n- ค่าความต้านทานดิน ≤5 โอห์ม',
        quantityMode: { type: 'fixed' as const, value: 1 },
      },
    ],
  };
}

function plumbingCategory() {
  return {
    no: 'E',
    description: 'งานระบบประปา / สุขาภิบาล',
    items: [
      {
        no: 'E.1',
        description: 'ท่อน้ำดี PPR PN10 ขนาด 20-25 มม.',
        unit: 'เมตร',
        unitPrice: 45,
        laborCost: 80,
        scopeDetails: '- ท่อ PPR PN10 (เกรด A)\n- ขนาด 20 มม. (แยกย่อย) / 25 มม. (เมน)\n- เชื่อมความร้อน (Heat Fusion)',
        quantityMode: { type: 'per-point' as const, pointsPerSqm: 0.5 },
      },
      {
        no: 'E.2',
        description: 'จุดจ่ายน้ำดี (อ่างล้างหน้า/ก๊อกซิงค์/ฝักบัว)',
        unit: 'จุด',
        unitPrice: 350,
        laborCost: 800,
        scopeDetails: '- วาล์วหัวจุด (Ball Valve)\n- ข้อต่อ/ข้องอ PPR\n- ฝังผนัง + ทดสอบแรงดัน\n- พร้อมฝาปิดหน้าจุด',
        quantityMode: { type: 'per-room' as const, defaultCount: 7 },
      },
      {
        no: 'E.3',
        description: 'ท่อทิ้งน้ำเสีย PVC 2"-4"',
        unit: 'เมตร',
        unitPrice: 60,
        laborCost: 100,
        scopeDetails: '- ท่อ PVC 2" (อ่างล้างหน้า/ซิงค์)\n- ท่อ PVC 4" (โถสุขภัณฑ์)\n- ข้อต่อ/ท่อดัก/กาว',
        quantityMode: { type: 'per-point' as const, pointsPerSqm: 0.3 },
      },
      {
        no: 'E.4',
        description: 'Trap กันกลิ่น (P-Trap / Floor Drain)',
        unit: 'ตัว',
        unitPrice: 350,
        laborCost: 200,
        scopeDetails: '- P-Trap PVC (อ่างล้างหน้า/ซิงค์)\n- Floor Drain สแตนเลส (พื้นห้องน้ำ)\n- กันกลิ่นย้อนกลับ',
        quantityMode: { type: 'per-room' as const, defaultCount: 4 },
      },
      {
        no: 'E.5',
        description: 'มิเตอร์น้ำ + วาล์วหลัก',
        unit: 'ชุด',
        unitPrice: 1500,
        laborCost: 800,
        scopeDetails: '- มิเตอร์น้ำ 1/2" - 3/4"\n- Gate Valve / Ball Valve เมน\n- ท่อเมนเข้าอาคาร',
        quantityMode: { type: 'fixed' as const, value: 1 },
      },
      {
        no: 'E.6',
        description: 'เครื่องทำน้ำอุ่น (ต่อห้องน้ำ)',
        unit: 'เครื่อง',
        unitPrice: 4500,
        laborCost: 1500,
        scopeDetails: '- เครื่องทำน้ำอุ่นไฟฟ้า 3,500-4,500W\n- ท่อน้ำเข้า-ออก\n- วงจรไฟฟ้าแยก (เบรกเกอร์ 32A)',
        quantityMode: { type: 'per-room' as const, defaultCount: 2 },
        isOptional: true,
      },
      {
        no: 'E.7',
        description: 'ถังเก็บน้ำ + ปั๊มน้ำ (ถ้าจำเป็น)',
        unit: 'ชุด',
        unitPrice: 8000,
        laborCost: 3000,
        scopeDetails: '- ถังเก็บน้ำ PE 1,000 ลิตร\n- ปั๊มน้ำอัตโนมัติ 250W\n- ถังแรงดัน\n- ท่อ + วาล์ว',
        quantityMode: { type: 'fixed' as const, value: 1 },
        isOptional: true,
      },
    ],
  };
}

function bathroomCategory() {
  return {
    no: 'F',
    description: 'งานห้องน้ำ',
    items: [
      {
        no: 'F.1',
        description: 'กันซึม Flex Seal / Dr. Fixit 2K (พื้น + ผนังสูง 30 ซม.)',
        unit: 'ตร.ม.',
        unitPrice: 250,
        laborCost: 450,
        scopeDetails: '- กันซึมอะคริลิค/โพลียูรีเทน 2 ชั้น\n- ทาพื้น + ผนังสูง 30 ซม.\n- เสริมตาข่ายมุมรอยต่อ\n- ทดสอบขังน้ำ 24-48 ชม.',
        quantityMode: { type: 'area-percentage' as const, percentage: 0.12 },
      },
      {
        no: 'F.2',
        description: 'ปูกระเบื้องพื้นห้องน้ำ 30×30 / 60×60 กันลื่น',
        unit: 'ตร.ม.',
        unitPrice: 500,
        laborCost: 450,
        scopeDetails: '- กระเบื้องพอร์ซเลน กันลื่น\n- กาวซีเมนต์ Weber/จระเข้\n- ยาแนว (สีขาว/เทา)\n- ทำระดับลาดเข้าท่อระบาย',
        quantityMode: { type: 'area-percentage' as const, percentage: 0.10 },
      },
      {
        no: 'F.3',
        description: 'ปูกระเบื้องผนังห้องน้ำ 30×60 / 60×120',
        unit: 'ตร.ม.',
        unitPrice: 650,
        laborCost: 500,
        scopeDetails: '- กระเบื้องพอร์ซเลน/เซรามิก\n- ปูผนังสูงเต็ม 2.4 ม.\n- กาวซีเมนต์ Weber/จระเข้\n- ยาแนว',
        quantityMode: { type: 'area-percentage' as const, percentage: 0.20 },
      },
      {
        no: 'F.4',
        description: 'โถสุขภัณฑ์ชิ้นเดียว (COTTO / American Standard)',
        unit: 'ชุด',
        unitPrice: 5500,
        laborCost: 1500,
        scopeDetails: '- สุขภัณฑ์ชิ้นเดียว สีขาว\n- ระบบ Dual Flush\n- ฝารองนั่ง Soft Close\n- ข้อต่อท่อน้ำ + สายอ่อน',
        quantityMode: { type: 'per-room' as const, defaultCount: 2 },
      },
      {
        no: 'F.5',
        description: 'อ่างล้างหน้าแบบฝัง / วางบนเคาน์เตอร์',
        unit: 'ชุด',
        unitPrice: 3500,
        laborCost: 1200,
        scopeDetails: '- อ่างล้างหน้า สีขาว (COTTO/AMS)\n- เคาน์เตอร์หินเทียม/หินแกรนิต\n- ขาตั้ง/ตู้ใต้อ่าง',
        quantityMode: { type: 'per-room' as const, defaultCount: 2 },
      },
      {
        no: 'F.6',
        description: 'ก๊อกน้ำอ่างล้างหน้า (ก้านโยก)',
        unit: 'ตัว',
        unitPrice: 1800,
        laborCost: 300,
        scopeDetails: '- ก๊อกน้ำก้านโยก สีโครม\n- ยี่ห้อ COTTO/AMS/OEM\n- สาย Flexible + วาล์ว',
        quantityMode: { type: 'per-room' as const, defaultCount: 2 },
      },
      {
        no: 'F.7',
        description: 'ชุดฝักบัวอาบน้ำ + ราวเลื่อน',
        unit: 'ชุด',
        unitPrice: 2200,
        laborCost: 500,
        scopeDetails: '- ฝักบัว 3-5 ระบบ\n- ราวเลื่อนสแตนเลส\n- สายอ่อน + ข้อต่อผนัง\n- วาล์วผสมน้ำร้อน-เย็น',
        quantityMode: { type: 'per-room' as const, defaultCount: 2 },
      },
      {
        no: 'F.8',
        description: 'กระจกเงาห้องน้ำ 50×70 ซม.',
        unit: 'บาน',
        unitPrice: 1200,
        laborCost: 300,
        scopeDetails: '- กระจกเงาใส 5 มม.\n- ขอบตัด Bevel/ขัดมัน\n- น็อตยึดสแตนเลส',
        quantityMode: { type: 'per-room' as const, defaultCount: 2 },
      },
      {
        no: 'F.9',
        description: 'อุปกรณ์ห้องน้ำ (ที่แขวนผ้า/สบู่/กระดาษ)',
        unit: 'ชุด',
        unitPrice: 1800,
        laborCost: 300,
        scopeDetails: '- ราวแขวนผ้า สแตนเลส\n- ที่ใส่สบู่\n- ที่ใส่กระดาษทิชชู\n- ตะขอแขวน',
        quantityMode: { type: 'per-room' as const, defaultCount: 2 },
      },
      {
        no: 'F.10',
        description: 'ประตูห้องน้ำ PVC / อลูมิเนียม',
        unit: 'บาน',
        unitPrice: 3500,
        laborCost: 800,
        scopeDetails: '- ประตู PVC เกล็ดระบายอากาศ / อลูมิเนียม\n- บานพับสแตนเลส\n- มือจับ + กลอน\n- วงกบ',
        quantityMode: { type: 'per-room' as const, defaultCount: 2 },
      },
    ],
  };
}

function ceilingCategory() {
  return {
    no: 'G',
    description: 'งานฝ้าเพดาน',
    items: [
      {
        no: 'G.1',
        description: 'ฝ้าเรียบ ยิปซั่มบอร์ด 9 มม. (โครงเหล็กชุบ)',
        unit: 'ตร.ม.',
        unitPrice: 120,
        laborCost: 350,
        scopeDetails: '- ยิปซั่มบอร์ด 9 มม. (ตราช้าง/ยิปรอค)\n- โครงเหล็กชุบ C-Line + Furring\n- สกรู/ตะปูเกลียว\n- ฉาบรอยต่อ + เทปกาว',
        quantityMode: { type: 'area-multiplier' as const, factor: 0.65 },
      },
      {
        no: 'G.2',
        description: 'ฝ้าหลุม / ฝ้าดรอป (Drop Ceiling) พร้อมร่องไฟ',
        unit: 'ตร.ม.',
        unitPrice: 200,
        laborCost: 550,
        scopeDetails: '- ยิปซั่มบอร์ด 9 มม. 2 ชั้น\n- โครงเหล็กชุบ 2 ระดับ\n- กัดร่อง LED Strip\n- ฉาบเก็บขอบ/มุม',
        quantityMode: { type: 'area-multiplier' as const, factor: 0.25 },
      },
      {
        no: 'G.3',
        description: 'ฝ้าห้องน้ำ แผ่นกันชื้น (Calcium Silicate)',
        unit: 'ตร.ม.',
        unitPrice: 180,
        laborCost: 400,
        scopeDetails: '- แผ่นแคลเซียมซิลิเกต 6 มม. (ตราช้าง สมาร์ทบอร์ด)\n- โครงเหล็กชุบ\n- ช่องเปิด Manhole (ตรวจท่อ/สาย)',
        quantityMode: { type: 'area-percentage' as const, percentage: 0.10 },
      },
      {
        no: 'G.4',
        description: 'บัวฝ้า / คิ้วเชิงผนัง PU',
        unit: 'เมตร',
        unitPrice: 60,
        laborCost: 40,
        scopeDetails: '- บัวเชิงผนัง PU โฟม / โพลีสไตรีน\n- กาวติดบัว\n- เก็บมุม/เก็บรอยต่อ\n- ทาสีทับ',
        quantityMode: { type: 'perimeter' as const, wallHeight: 0.3 },
        isOptional: true,
      },
    ],
  };
}

function flooringCategory() {
  return {
    no: 'H',
    description: 'งานพื้น',
    items: [
      {
        no: 'H.1',
        description: 'ปูพื้น SPC Click Lock 4 มม. (Vinyl Plank)',
        unit: 'ตร.ม.',
        unitPrice: 350,
        laborCost: 180,
        scopeDetails: '- พื้น SPC 4 มม. ลายไม้ (Click Lock)\n- Underlay PE Foam 2 มม.\n- เว้นรอยต่อขยาย 5-8 มม.\n- รับประกัน 10-15 ปี',
        quantityMode: { type: 'area-multiplier' as const, factor: 0.70 },
      },
      {
        no: 'H.2',
        description: 'ปูพื้นลามิเนต 8-12 มม. (Laminate)',
        unit: 'ตร.ม.',
        unitPrice: 450,
        laborCost: 200,
        scopeDetails: '- ลามิเนตหนา 8-12 มม. (AC4-AC5)\n- Underlay PE Foam\n- Click Lock / Drop Lock\n- รับประกัน 15-20 ปี',
        quantityMode: { type: 'area-multiplier' as const, factor: 0 },
        isOptional: true,
      },
      {
        no: 'H.3',
        description: 'ปูกระเบื้องพื้น 60×60 พอร์ซเลน (ห้องครัว/ทางเดิน)',
        unit: 'ตร.ม.',
        unitPrice: 500,
        laborCost: 400,
        scopeDetails: '- กระเบื้องพอร์ซเลน 60×60\n- กาวซีเมนต์ Weber/จระเข้\n- ยาแนว\n- ใช้สำหรับพื้นที่เปียก/ครัว',
        quantityMode: { type: 'area-multiplier' as const, factor: 0.15 },
        isOptional: true,
      },
      {
        no: 'H.4',
        description: 'บัวเชิงผนัง PVC / MDF',
        unit: 'เมตร',
        unitPrice: 55,
        laborCost: 35,
        scopeDetails: '- บัวเชิงผนัง PVC/MDF สูง 6-8 ซม.\n- จบขอบ T-bar (ถ้ามี)\n- กาว + ตะปูเกลียว',
        quantityMode: { type: 'perimeter' as const, wallHeight: 0.3 },
      },
      {
        no: 'H.5',
        description: 'ปรับระดับพื้น Self-Leveling (ถ้าจำเป็น)',
        unit: 'ตร.ม.',
        unitPrice: 180,
        laborCost: 120,
        scopeDetails: '- ปูนปรับระดับ Self-Leveling\n- หนา 3-10 มม.\n- ใช้เมื่อพื้นไม่เรียบ/ไม่ได้ระดับ',
        quantityMode: { type: 'area-multiplier' as const, factor: 0.3 },
        isOptional: true,
      },
    ],
  };
}

function paintCategory() {
  return {
    no: 'I',
    description: 'งานสี',
    items: [
      {
        no: 'I.1',
        description: 'โป๊วผิว + ขัดผนัง (ปรับผิวเรียบ)',
        unit: 'ตร.ม.',
        unitPrice: 20,
        laborCost: 50,
        scopeDetails: '- โป๊วผิว 1-2 รอบ (ตราจระเข้/TOA)\n- ขัดกระดาษทราย เบอร์ 180-240\n- ปรับผิวผนังให้เรียบสม่ำเสมอ',
        quantityMode: { type: 'perimeter' as const, wallHeight: 2.8 },
      },
      {
        no: 'I.2',
        description: 'สีรองพื้นปูนใหม่ (Primer/Sealer)',
        unit: 'ตร.ม.',
        unitPrice: 15,
        laborCost: 25,
        scopeDetails: '- สีรองพื้นปูนใหม่ 1 รอบ\n- TOA / Nippon / Jotun\n- ป้องกันด่างปูน/ความชื้น',
        quantityMode: { type: 'perimeter' as const, wallHeight: 2.8 },
      },
      {
        no: 'I.3',
        description: 'สีผนังภายใน 2-3 รอบ (สีน้ำอะครีลิค)',
        unit: 'ตร.ม.',
        unitPrice: 30,
        laborCost: 55,
        scopeDetails: '- สีน้ำอะครีลิค 100% (TOA 4 Seasons/Nippon Matex)\n- ทา 2-3 รอบ\n- สีขาว/สีอ่อนตามเลือก\n- เช็ดล้างได้',
        quantityMode: { type: 'perimeter' as const, wallHeight: 2.8 },
      },
      {
        no: 'I.4',
        description: 'สีฝ้าเพดาน 2 รอบ (สีขาว)',
        unit: 'ตร.ม.',
        unitPrice: 20,
        laborCost: 40,
        scopeDetails: '- สีน้ำทาฝ้า (TOA Ceiling Paint)\n- ทา 2 รอบ\n- สีขาวเรียบ\n- ไม่สะท้อนแสง',
        quantityMode: { type: 'area-multiplier' as const, factor: 0.85 },
      },
      {
        no: 'I.5',
        description: 'สีภายนอก 2-3 รอบ (สีกันแดด/กันน้ำ)',
        unit: 'ตร.ม.',
        unitPrice: 45,
        laborCost: 65,
        scopeDetails: '- สีภายนอกกันแดด/กันน้ำ (TOA Supertech/Jotun)\n- ทา 2-3 รอบ\n- ทนแดด/ฝน 5-7 ปี\n- สีตามเลือก',
        quantityMode: { type: 'perimeter' as const, wallHeight: 1.5 },
        isOptional: true,
      },
    ],
  };
}

function cleanupCategory() {
  return {
    no: 'J',
    description: 'งานเก็บงาน / ทำความสะอาด',
    items: [
      {
        no: 'J.1',
        description: 'Defect ครั้งที่ 1 (ตรวจสอบ + แก้ไข)',
        unit: 'ครั้ง',
        unitPrice: 0,
        laborCost: 3000,
        scopeDetails: '- ตรวจสอบงานทุกระบบ\n- ทำ Punch List\n- แก้ไขรอยบิ่น/แตก/ร้าว\n- ซ่อมแซมจุดบกพร่อง',
        quantityMode: { type: 'fixed' as const, value: 1 },
      },
      {
        no: 'J.2',
        description: 'Defect ครั้งที่ 2 (ตรวจซ้ำ + เก็บงาน)',
        unit: 'ครั้ง',
        unitPrice: 0,
        laborCost: 2000,
        scopeDetails: '- ตรวจสอบจุดที่แก้ไขแล้ว\n- แก้ไขจุดที่เหลือ\n- Touch Up สี/ยาแนว\n- เก็บขอบ/มุม',
        quantityMode: { type: 'fixed' as const, value: 1 },
      },
      {
        no: 'J.3',
        description: 'Big Cleaning + ขนย้ายเศษวัสดุ',
        unit: 'งาน',
        unitPrice: 2000,
        laborCost: 6000,
        scopeDetails: '- ทำความสะอาดทั้งหมด\n- เช็ดกระจก/ผนัง/พื้น\n- ขัดพื้น/เคลือบพื้น (ถ้ามี)\n- ขนเศษวัสดุ + ทิ้ง',
        quantityMode: { type: 'fixed' as const, value: 1 },
      },
    ],
  };
}

function builtInCategory() {
  return {
    no: 'K',
    description: 'งานเฟอร์นิเจอร์บิ้วอิน',
    isOptional: true,
    items: [
      {
        no: 'K.1',
        description: 'ตู้เสื้อผ้าบิ้วอิน 2.0×2.4 ม. (บานเปิด)',
        unit: 'ชุด',
        unitPrice: 28000,
        laborCost: 7000,
        scopeDetails: '- โครงไม้อัด/ไม้ MDF\n- หน้าบาน Melamine/Laminate\n- ชั้นวางเสื้อผ้า + ราวแขวน\n- ลิ้นชัก 2-3 ใบ\n- บานพับ Soft Close\n- ขนาดกว้างประมาณ 2.0 ม. สูง 2.4 ม.',
        quantityMode: { type: 'per-room' as const, defaultCount: 2 },
      },
      {
        no: 'K.2',
        description: 'ตู้เสื้อผ้าบิ้วอิน 2.0×2.4 ม. (บานเลื่อน)',
        unit: 'ชุด',
        unitPrice: 35000,
        laborCost: 8000,
        scopeDetails: '- โครงไม้อัด/ไม้ MDF\n- บานเลื่อน Melamine + รางอลูมิเนียม\n- กระจกเงา (ถ้ามี)\n- ชั้นวาง + ราวแขวน + ลิ้นชัก',
        quantityMode: { type: 'fixed' as const, value: 1 },
        isOptional: true,
      },
      {
        no: 'K.3',
        description: 'ชุดครัว ตู้ล่าง + Top หินควอตซ์ (~3 ม.)',
        unit: 'ชุด',
        unitPrice: 45000,
        laborCost: 8000,
        scopeDetails: '- ตู้ล่าง Melamine 3 ม.\n- Top หินควอตซ์ / หินเทียม\n- อ่างล้างจาน สแตนเลส\n- บานพับ Soft Close / รางลิ้นชักเต็ม',
        quantityMode: { type: 'fixed' as const, value: 1 },
      },
      {
        no: 'K.4',
        description: 'ชุดครัว ตู้ลอย (~3 ม.)',
        unit: 'ชุด',
        unitPrice: 22000,
        laborCost: 5000,
        scopeDetails: '- ตู้ลอย Melamine 3 ม.\n- บานพับ Soft Close\n- ชั้นปรับระดับ\n- ยึดผนัง Fisher',
        quantityMode: { type: 'fixed' as const, value: 1 },
      },
      {
        no: 'K.5',
        description: 'ชั้นวางทีวี / ตู้โชว์ บิ้วอิน (~2.5-3.5 ม.)',
        unit: 'ชุด',
        unitPrice: 38000,
        laborCost: 7000,
        scopeDetails: '- ชั้นวาง + ช่องเก็บของ\n- ช่องซ่อนสายไฟ/สาย HDMI\n- ไฟ LED ในตู้ (ถ้ามี)\n- Melamine/Laminate',
        quantityMode: { type: 'fixed' as const, value: 1 },
      },
      {
        no: 'K.6',
        description: 'ตู้รองเท้าบิ้วอิน',
        unit: 'ชุด',
        unitPrice: 12000,
        laborCost: 3000,
        scopeDetails: '- ตู้รองเท้า Melamine\n- ชั้นปรับระดับ 5-6 ชั้น\n- บานเปิด/ลิ้นชัก\n- ขนาดกว้าง 80-120 ซม.',
        quantityMode: { type: 'fixed' as const, value: 1 },
        isOptional: true,
      },
      {
        no: 'K.7',
        description: 'เคาน์เตอร์ Vanity ห้องน้ำ บิ้วอิน',
        unit: 'ชุด',
        unitPrice: 15000,
        laborCost: 4000,
        scopeDetails: '- Top หินเทียม/หินควอตซ์\n- ตู้เก็บของใต้อ่าง\n- กันน้ำ/กันชื้น',
        quantityMode: { type: 'per-room' as const, defaultCount: 1 },
        isOptional: true,
      },
    ],
  };
}

function acCategory() {
  return {
    no: 'L',
    description: 'ระบบปรับอากาศ',
    isOptional: true,
    items: [
      {
        no: 'L.1',
        description: 'แอร์ผนัง Inverter 9,000 BTU + ติดตั้ง (ห้องเล็ก)',
        unit: 'เครื่อง',
        unitPrice: 15000,
        laborCost: 4000,
        scopeDetails: '- แอร์ผนัง Inverter 9,000 BTU\n- ยี่ห้อ Daikin/Mitsubishi/Samsung\n- เดินท่อทองแดง ≤5 ม.\n- เดินสายไฟแยกวงจร\n- รับประกันคอมเพรสเซอร์ 5 ปี',
        quantityMode: { type: 'fixed' as const, value: 1 },
        isOptional: true,
      },
      {
        no: 'L.2',
        description: 'แอร์ผนัง Inverter 12,000 BTU + ติดตั้ง (ห้องนอน)',
        unit: 'เครื่อง',
        unitPrice: 18000,
        laborCost: 4500,
        scopeDetails: '- แอร์ผนัง Inverter 12,000 BTU\n- ยี่ห้อ Daikin/Mitsubishi/Samsung\n- เดินท่อทองแดง ≤5 ม.\n- เดินสายไฟแยกวงจร',
        quantityMode: { type: 'per-room' as const, defaultCount: 2 },
      },
      {
        no: 'L.3',
        description: 'แอร์ผนัง Inverter 18,000 BTU + ติดตั้ง (ห้องใหญ่/ลิฟวิ่ง)',
        unit: 'เครื่อง',
        unitPrice: 24000,
        laborCost: 5000,
        scopeDetails: '- แอร์ผนัง Inverter 18,000 BTU\n- ยี่ห้อ Daikin/Mitsubishi/Samsung\n- เดินท่อทองแดง ≤7 ม.\n- เดินสายไฟแยกวงจร',
        quantityMode: { type: 'fixed' as const, value: 1 },
      },
      {
        no: 'L.4',
        description: 'ท่อทองแดงเพิ่มเติม (กรณีเดินท่อไกล)',
        unit: 'เมตร',
        unitPrice: 350,
        laborCost: 150,
        scopeDetails: '- ท่อทองแดง + ฉนวนหุ้ม\n- ท่อ Drain PVC\n- สายไฟ VCT\n- ติดตั้ง + เก็บงาน',
        quantityMode: { type: 'fixed' as const, value: 10 },
        isOptional: true,
      },
    ],
  };
}

// ===== HOUSE-SPECIFIC CATEGORIES =====

function structureCategory() {
  return {
    no: 'M',
    description: 'งานโครงสร้าง',
    items: [
      {
        no: 'M.1',
        description: 'เสาเข็ม I-180 / สปันไมโครไพล์ ยาว 6-8 ม.',
        unit: 'ต้น',
        unitPrice: 2800,
        laborCost: 1200,
        scopeDetails: '- เสาเข็ม I-180 ยาว 6-8 ม. / สปันไมโครไพล์ Ø25-30 ซม.\n- ตอกหรือเจาะตามสภาพดิน\n- ทดสอบ Dynamic Load Test',
        quantityMode: { type: 'area-multiplier' as const, factor: 0.15 },
      },
      {
        no: 'M.2',
        description: 'ฐานราก คสล. (ฐานแผ่/ฐานเสาเข็ม)',
        unit: 'ตร.ม.',
        unitPrice: 800,
        laborCost: 600,
        scopeDetails: '- คอนกรีตผสมเสร็จ 240 ksc\n- เหล็กข้ออ้อย DB12-DB16\n- ไม้แบบ/แบบเหล็ก\n- ตอม่อ คสล.',
        quantityMode: { type: 'area-multiplier' as const, factor: 1 },
      },
      {
        no: 'M.3',
        description: 'เสา คสล. (เหล็ก DB12-DB16 + ปลอก RB6)',
        unit: 'ตร.ม.',
        unitPrice: 900,
        laborCost: 700,
        scopeDetails: '- เสา คสล. 20×20 / 25×25 ซม.\n- เหล็กยืน DB12-DB16 (4-8 เส้น)\n- เหล็กปลอก RB6 @15 ซม.\n- คอนกรีตผสมเสร็จ 240 ksc',
        quantityMode: { type: 'area-multiplier' as const, factor: 0.3 },
      },
      {
        no: 'M.4',
        description: 'คาน คสล. (เหล็ก DB12-DB16 + ปลอก RB6)',
        unit: 'ตร.ม.',
        unitPrice: 850,
        laborCost: 650,
        scopeDetails: '- คาน คสล. 15×30 / 20×40 ซม.\n- เหล็กยืน DB12-DB16 (3-6 เส้น)\n- เหล็กปลอก RB6 @15 ซม.\n- ไม้แบบ/ค้ำยัน',
        quantityMode: { type: 'area-multiplier' as const, factor: 0.5 },
      },
      {
        no: 'M.5',
        description: 'พื้น คสล. หนา 10-12 ซม. (Wire Mesh/ตะแกรง)',
        unit: 'ตร.ม.',
        unitPrice: 600,
        laborCost: 500,
        scopeDetails: '- พื้น คสล. หล่อในที่ หนา 10-12 ซม.\n- ตะแกรงเหล็ก Wire Mesh 4 มม. @20 ซม.\n- คอนกรีตผสมเสร็จ 240 ksc\n- ไม้แบบพื้น + ค้ำยัน',
        quantityMode: { type: 'area-multiplier' as const, factor: 1 },
      },
      {
        no: 'M.6',
        description: 'บันได คสล. (ถ้ามี)',
        unit: 'ชุด',
        unitPrice: 25000,
        laborCost: 15000,
        scopeDetails: '- โครงสร้างบันได คสล.\n- เหล็ก DB12 + ปลอก RB6\n- 12-15 ขั้น\n- ราวบันไดเหล็ก/สแตนเลส',
        quantityMode: { type: 'fixed' as const, value: 1 },
        isOptional: true,
      },
      {
        no: 'M.7',
        description: 'โครงหลังคาเหล็กสำเร็จรูป (Light Gauge Steel)',
        unit: 'ตร.ม.',
        unitPrice: 550,
        laborCost: 350,
        scopeDetails: '- โครงเหล็กสำเร็จรูป (Light Gauge/C-Purlin)\n- จันทัน + แป + ระแนง\n- น็อต/สกรู/แผ่นเพลท\n- คำนวณโครงสร้าง',
        quantityMode: { type: 'area-multiplier' as const, factor: 1.15 },
      },
      {
        no: 'M.8',
        description: 'หลังคาเมทัลชีท 0.35-0.47 มม.',
        unit: 'ตร.ม.',
        unitPrice: 220,
        laborCost: 120,
        scopeDetails: '- เมทัลชีท BlueScope/NS BlueScope\n- หนา 0.35-0.47 มม.\n- สกรูหกเหลี่ยม + แหวนยาง\n- สีมาตรฐาน/สีพิเศษ',
        quantityMode: { type: 'area-multiplier' as const, factor: 1.15 },
      },
      {
        no: 'M.9',
        description: 'ฉนวนกันความร้อน PE Foam 10 มม. (ใต้หลังคา)',
        unit: 'ตร.ม.',
        unitPrice: 65,
        laborCost: 25,
        scopeDetails: '- ฉนวน PE Foam หนา 10 มม. แบบมี Foil\n- ลดความร้อน 3-5 องศา\n- ติดใต้เมทัลชีท',
        quantityMode: { type: 'area-multiplier' as const, factor: 1.15 },
      },
      {
        no: 'M.10',
        description: 'ครอบสันหลังคา + ครอบข้าง + รางน้ำฝน',
        unit: 'เมตร',
        unitPrice: 250,
        laborCost: 120,
        scopeDetails: '- ครอบสันหลังคาเมทัลชีท\n- ครอบชายคา/ครอบข้าง\n- รางน้ำฝน PVC/สังกะสี\n- ท่อน้ำฝน',
        quantityMode: { type: 'perimeter' as const, wallHeight: 0.5 },
      },
    ],
  };
}

function exteriorCategory() {
  return {
    no: 'N',
    description: 'งานภายนอก / ประตู-หน้าต่าง',
    isOptional: true,
    items: [
      {
        no: 'N.1',
        description: 'ผนังภายนอก อิฐมวลเบา + ฉาบ + ทาสี',
        unit: 'ตร.ม.',
        unitPrice: 200,
        laborCost: 350,
        scopeDetails: '- อิฐมวลเบา 10 ซม.\n- ฉาบปูน 2 ด้าน\n- ทาสีภายนอกกันแดด/กันน้ำ',
        quantityMode: { type: 'perimeter' as const, wallHeight: 3.0 },
      },
      {
        no: 'N.2',
        description: 'ประตูบานเปิด อลูมิเนียม + กระจก',
        unit: 'ชุด',
        unitPrice: 8000,
        laborCost: 2000,
        scopeDetails: '- กรอบอลูมิเนียม (สีดำ/น้ำตาล)\n- กระจกใส 6 มม.\n- มือจับ/บานพับ/กลอน\n- วงกบ + ยาแนว',
        quantityMode: { type: 'fixed' as const, value: 2 },
      },
      {
        no: 'N.3',
        description: 'ประตูบานเลื่อน อลูมิเนียม + กระจก Tempered',
        unit: 'ชุด',
        unitPrice: 15000,
        laborCost: 3000,
        scopeDetails: '- กรอบอลูมิเนียม\n- กระจก Tempered 8-10 มม.\n- รางเลื่อน + ล้อ\n- กุญแจล็อค\n- ขนาดประมาณ 2.0-2.4 ม.',
        quantityMode: { type: 'fixed' as const, value: 2 },
      },
      {
        no: 'N.4',
        description: 'หน้าต่างบานเลื่อน อลูมิเนียม + กระจก',
        unit: 'ชุด',
        unitPrice: 5500,
        laborCost: 1500,
        scopeDetails: '- กรอบอลูมิเนียม\n- กระจกใส 6 มม.\n- มุ้งลวดกันยุง\n- ล็อค + มือจับ',
        quantityMode: { type: 'per-room' as const, defaultCount: 6 },
      },
      {
        no: 'N.5',
        description: 'ประตูไม้จริง / ประตู HDF (ภายใน)',
        unit: 'บาน',
        unitPrice: 5000,
        laborCost: 1200,
        scopeDetails: '- ประตู HDF / ไม้จริง\n- วงกบไม้/เหล็ก\n- บานพับ 3 ตัว\n- ลูกบิด/มือจับ + กลอน',
        quantityMode: { type: 'per-room' as const, defaultCount: 5 },
      },
      {
        no: 'N.6',
        description: 'ประตูหน้าบ้าน (ประตูเหล็ก/ไม้สัก)',
        unit: 'ชุด',
        unitPrice: 15000,
        laborCost: 3000,
        scopeDetails: '- ประตูเหล็กหล่อ/ไม้สัก\n- Digital Door Lock / กลอนหลายจุด\n- วงกบเหล็ก\n- บานพับ Heavy Duty',
        quantityMode: { type: 'fixed' as const, value: 1 },
      },
    ],
  };
}

function landscapeCategory() {
  return {
    no: 'O',
    description: 'งาน Landscape / รั้ว / ที่จอดรถ',
    isOptional: true,
    items: [
      {
        no: 'O.1',
        description: 'รั้วคอนกรีต + เหล็กดัด / รั้วสำเร็จรูป',
        unit: 'เมตร',
        unitPrice: 3000,
        laborCost: 1200,
        scopeDetails: '- เสารั้ว คสล. @3 ม.\n- แผ่นรั้วคอนกรีต/เหล็กดัด\n- ทาสีกันสนิม + สีจริง',
        quantityMode: { type: 'fixed' as const, value: 40 },
      },
      {
        no: 'O.2',
        description: 'ประตูรั้ว เลื่อน/สวิง + รีโมท',
        unit: 'ชุด',
        unitPrice: 25000,
        laborCost: 8000,
        scopeDetails: '- ประตูรั้วเลื่อนเหล็ก/สแตนเลส\n- มอเตอร์ + รีโมทคอนโทรล\n- ราง + ล้อ\n- ขนาด 3-4 ม.',
        quantityMode: { type: 'fixed' as const, value: 1 },
      },
      {
        no: 'O.3',
        description: 'ลานจอดรถ / ทางเดิน คอนกรีตเสริมเหล็ก',
        unit: 'ตร.ม.',
        unitPrice: 400,
        laborCost: 250,
        scopeDetails: '- คอนกรีตผสมเสร็จ หนา 10-15 ซม.\n- ตะแกรงเหล็ก Wire Mesh\n- บดอัดดินรองพื้น\n- ตัดแนว (Joint) ทุก 3 ม.',
        quantityMode: { type: 'area-multiplier' as const, factor: 0.25 },
      },
      {
        no: 'O.4',
        description: 'ท่อระบายน้ำ + บ่อพัก',
        unit: 'เมตร',
        unitPrice: 500,
        laborCost: 300,
        scopeDetails: '- ท่อ PVC 6"-8"\n- บ่อพัก คสล. ทุก 6-8 ม.\n- ฝาตะแกรง',
        quantityMode: { type: 'fixed' as const, value: 20 },
        isOptional: true,
      },
    ],
  };
}

function poolCategory() {
  return {
    no: 'P',
    description: 'สระว่ายน้ำ',
    isOptional: true,
    items: [
      {
        no: 'P.1',
        description: 'สระว่ายน้ำ คสล. ขนาด 3×6 ม. ลึก 1.2-1.5 ม.',
        unit: 'ชุด',
        unitPrice: 180000,
        laborCost: 70000,
        scopeDetails: '- ขุดดิน + โครงสร้าง คสล.\n- กันซึม Crystalline\n- ปูกระเบื้องโมเสค\n- ท่อ + วาล์ว',
        quantityMode: { type: 'fixed' as const, value: 1 },
      },
      {
        no: 'P.2',
        description: 'ระบบกรองน้ำ (Sand Filter + Pump)',
        unit: 'ชุด',
        unitPrice: 35000,
        laborCost: 10000,
        scopeDetails: '- ถังกรองทราย (Sand Filter)\n- ปั๊มน้ำ 1-1.5 HP\n- วาล์วหลายทาง (Multi-port Valve)\n- ท่อ PVC + ข้อต่อ',
        quantityMode: { type: 'fixed' as const, value: 1 },
      },
      {
        no: 'P.3',
        description: 'ไฟใต้น้ำ LED + ระบบไฟฟ้าสระ',
        unit: 'ชุด',
        unitPrice: 8000,
        laborCost: 4000,
        scopeDetails: '- ไฟใต้น้ำ LED 12V\n- หม้อแปลงไฟ\n- สาย Submersible\n- ELCB กันไฟดูด',
        quantityMode: { type: 'fixed' as const, value: 1 },
      },
    ],
  };
}

// ===== OFFICE-SPECIFIC =====

function partitionCategory() {
  return {
    no: 'M',
    description: 'งานพาร์ทิชั่น / ผนังกระจก',
    items: [
      {
        no: 'M.1',
        description: 'ผนังกั้นห้อง ยิปซั่มบอร์ด 2 ด้าน + ฉนวน',
        unit: 'ตร.ม.',
        unitPrice: 550,
        laborCost: 350,
        scopeDetails: '- โครง C-Stud 65 มม.\n- ยิปซั่มบอร์ด 9 มม. 2 ด้าน\n- ฉนวนใยแก้ว 25 มม. (กันเสียง)\n- ฉาบรอยต่อ + เทปกาว',
        quantityMode: { type: 'area-multiplier' as const, factor: 0.35 },
      },
      {
        no: 'M.2',
        description: 'ผนังกระจก Tempered 10 มม. + กรอบอลูมิเนียม',
        unit: 'ตร.ม.',
        unitPrice: 3200,
        laborCost: 1000,
        scopeDetails: '- กระจก Tempered 10 มม.\n- กรอบอลูมิเนียมสีดำ/สีเงิน\n- ซิลิโคนยาแนว\n- ฟิล์มฝ้า/สติ๊กเกอร์ (ถ้ามี)',
        quantityMode: { type: 'area-multiplier' as const, factor: 0.12 },
        isOptional: true,
      },
      {
        no: 'M.3',
        description: 'ประตูกระจก Tempered บานผลัก/บานเปิด',
        unit: 'บาน',
        unitPrice: 8500,
        laborCost: 2500,
        scopeDetails: '- กระจก Tempered 12 มม.\n- อุปกรณ์ Floor Spring / Patch Fitting\n- มือจับสแตนเลส\n- กุญแจล็อค',
        quantityMode: { type: 'fixed' as const, value: 2 },
        isOptional: true,
      },
    ],
  };
}

function itCategory() {
  return {
    no: 'N',
    description: 'ระบบ IT / สาย LAN / CCTV',
    isOptional: true,
    items: [
      {
        no: 'N.1',
        description: 'เดินสาย LAN Cat6 + แผงปลั๊ก RJ45',
        unit: 'จุด',
        unitPrice: 600,
        laborCost: 400,
        scopeDetails: '- สาย Cat6 UTP (Commscope/AMP)\n- หัว RJ45 + แผงปลั๊ก\n- ท่อร้อยสาย PVC\n- ทดสอบ Fluke Test',
        quantityMode: { type: 'per-point' as const, pointsPerSqm: 0.25 },
      },
      {
        no: 'N.2',
        description: 'Patch Panel 24 Port + Rack 9U',
        unit: 'ชุด',
        unitPrice: 8000,
        laborCost: 3000,
        scopeDetails: '- Rack 9U/15U ติดผนัง\n- Patch Panel 24 Port\n- สาย Patch Cord\n- พัดลมระบายความร้อน',
        quantityMode: { type: 'fixed' as const, value: 1 },
      },
      {
        no: 'N.3',
        description: 'กล้อง CCTV IP 2MP + NVR',
        unit: 'ตัว',
        unitPrice: 4000,
        laborCost: 1500,
        scopeDetails: '- กล้อง IP Camera 2MP (Hikvision/Dahua)\n- สาย Cat6 + PoE\n- NVR 4/8 CH (คิดเฉลี่ยต่อกล้อง)\n- HDD 2TB (คิดเฉลี่ย)',
        quantityMode: { type: 'fixed' as const, value: 4 },
      },
      {
        no: 'N.4',
        description: 'Access Point WiFi 6 + ติดตั้ง',
        unit: 'ตัว',
        unitPrice: 3500,
        laborCost: 1000,
        scopeDetails: '- Access Point WiFi 6 (TP-Link/Ubiquiti)\n- PoE Switch Port\n- ติดตั้งฝังฝ้า/ติดผนัง\n- ตั้งค่า SSID/Password',
        quantityMode: { type: 'fixed' as const, value: 2 },
        isOptional: true,
      },
    ],
  };
}

// ===== COMMERCIAL-SPECIFIC =====

function facadeCategory() {
  return {
    no: 'M',
    description: 'งาน Facade / ป้าย',
    items: [
      {
        no: 'M.1',
        description: 'Facade กระจก + อลูมิเนียม Curtain Wall',
        unit: 'ตร.ม.',
        unitPrice: 4000,
        laborCost: 1200,
        scopeDetails: '- กรอบอลูมิเนียม Curtain Wall\n- กระจก Tempered/Laminate 8-10 มม.\n- ซิลิโคนยาแนว Structural\n- โครงเหล็กรอง (ถ้ามี)',
        quantityMode: { type: 'area-multiplier' as const, factor: 0.20 },
      },
      {
        no: 'M.2',
        description: 'ผนัง Composite Panel (ACP/ACM)',
        unit: 'ตร.ม.',
        unitPrice: 2500,
        laborCost: 800,
        scopeDetails: '- แผ่น Aluminium Composite Panel 4 มม.\n- โครงรอง อลูมิเนียม/เหล็กชุบ\n- สีตามเลือก\n- ซิลิโคนยาแนว',
        quantityMode: { type: 'area-multiplier' as const, factor: 0.15 },
        isOptional: true,
      },
      {
        no: 'M.3',
        description: 'ป้ายหน้าร้าน / Signage LED',
        unit: 'ชุด',
        unitPrice: 20000,
        laborCost: 8000,
        scopeDetails: '- ตัวอักษรนูน อะครีลิค/สแตนเลส\n- ไฟ LED ส่องหลัง/ส่องหน้า\n- โครงเหล็กรองรับ\n- สายไฟ + Transformer',
        quantityMode: { type: 'fixed' as const, value: 1 },
      },
    ],
  };
}

function fireProtectionCategory() {
  return {
    no: 'N',
    description: 'ระบบดับเพลิง / Fire Protection',
    items: [
      {
        no: 'N.1',
        description: 'Smoke Detector + สายสัญญาณ',
        unit: 'จุด',
        unitPrice: 1500,
        laborCost: 600,
        scopeDetails: '- Smoke Detector Photo-electric\n- สายสัญญาณ Fire Alarm\n- ท่อร้อยสาย\n- ฐานเสียบ',
        quantityMode: { type: 'per-point' as const, pointsPerSqm: 0.12 },
      },
      {
        no: 'N.2',
        description: 'Fire Alarm Panel 4-8 Zone',
        unit: 'ชุด',
        unitPrice: 12000,
        laborCost: 3000,
        scopeDetails: '- ตู้ Fire Alarm Panel 4-8 Zone\n- Battery Backup\n- กระดิ่ง/ไซเรน\n- Manual Call Point 2 จุด',
        quantityMode: { type: 'fixed' as const, value: 1 },
      },
      {
        no: 'N.3',
        description: 'ถังดับเพลิงผงเคมีแห้ง 10 ปอนด์',
        unit: 'ถัง',
        unitPrice: 1800,
        laborCost: 300,
        scopeDetails: '- ถังดับเพลิงผงเคมีแห้ง ABC 10 ปอนด์\n- ตู้/ที่แขวนผนัง\n- ป้ายบอกตำแหน่ง\n- ติดตั้งทุก 20 ม.',
        quantityMode: { type: 'fixed' as const, value: 4 },
      },
      {
        no: 'N.4',
        description: 'ป้ายทางหนีไฟ / ไฟฉุกเฉิน',
        unit: 'จุด',
        unitPrice: 1200,
        laborCost: 400,
        scopeDetails: '- ป้ายทางหนีไฟ EXIT เรืองแสง\n- ไฟฉุกเฉิน LED + Battery\n- ติดตั้งตามมาตรฐาน วสท.',
        quantityMode: { type: 'fixed' as const, value: 6 },
      },
    ],
  };
}

// ===== 6 CONSTRUCTION TEMPLATES =====

export const singleHouseTemplate: ConstructionTemplate = {
  id: 'single-house',
  name: 'บ้านเดี่ยว',
  nameEn: 'Single House',
  icon: 'Home',
  coverImage: '/images/templates/singlehouse.jpg',
  description: 'สร้างบ้านเดี่ยวใหม่ ครบทุกงาน ตั้งแต่โครงสร้างจนถึงตกแต่ง',
  referenceArea: 200,
  minArea: 120,
  maxArea: 500,
  defaultRooms: 3,
  defaultBathrooms: 2,
  categories: [
    designCategory(),
    demolitionCategory(true),
    structureCategory(),
    masonryCategory(),
    electricalCategory(),
    plumbingCategory(),
    bathroomCategory(),
    ceilingCategory(),
    flooringCategory(),
    paintCategory(),
    cleanupCategory(),
    builtInCategory(),
    acCategory(),
    exteriorCategory(),
    landscapeCategory(),
    poolCategory(),
  ],
  workPlanPhases: [
    { task: 'ออกแบบ/แบบก่อสร้าง', categoryRef: 'A', weeksPerHundredSqm: 3, minWeeks: 2, maxWeeks: 6, symbol: '■' },
    { task: 'เตรียมพื้นที่/ฐานราก', categoryRef: 'B', weeksPerHundredSqm: 2, minWeeks: 2, maxWeeks: 4, symbol: '□' },
    { task: 'โครงสร้าง คสล.', categoryRef: 'M', weeksPerHundredSqm: 6, minWeeks: 4, maxWeeks: 12, symbol: '□' },
    { task: 'ก่อผนัง/ฉาบ', categoryRef: 'C', weeksPerHundredSqm: 3, minWeeks: 2, maxWeeks: 6, symbol: '□' },
    { task: 'ไฟฟ้า', categoryRef: 'D', weeksPerHundredSqm: 2, minWeeks: 1, maxWeeks: 4, symbol: '□' },
    { task: 'ประปา', categoryRef: 'E', weeksPerHundredSqm: 2, minWeeks: 1, maxWeeks: 3, symbol: '□' },
    { task: 'ห้องน้ำ', categoryRef: 'F', weeksPerHundredSqm: 2, minWeeks: 2, maxWeeks: 4, symbol: '□' },
    { task: 'ฝ้าเพดาน', categoryRef: 'G', weeksPerHundredSqm: 2, minWeeks: 1, maxWeeks: 4, symbol: '□' },
    { task: 'พื้น', categoryRef: 'H', weeksPerHundredSqm: 1.5, minWeeks: 1, maxWeeks: 3, symbol: '□' },
    { task: 'ทาสี', categoryRef: 'I', weeksPerHundredSqm: 2, minWeeks: 1, maxWeeks: 4, symbol: '□' },
    { task: 'เฟอร์นิเจอร์บิ้วอิน', categoryRef: 'K', weeksPerHundredSqm: 3, minWeeks: 2, maxWeeks: 6, symbol: '■' },
    { task: 'แอร์', categoryRef: 'L', weeksPerHundredSqm: 0.5, minWeeks: 1, maxWeeks: 2, symbol: '□' },
    { task: 'ภายนอก/ประตู-หน้าต่าง', categoryRef: 'N', weeksPerHundredSqm: 3, minWeeks: 2, maxWeeks: 6, symbol: '□' },
    { task: 'Landscape/รั้ว', categoryRef: 'O', weeksPerHundredSqm: 2, minWeeks: 1, maxWeeks: 4, symbol: '□' },
    { task: 'เก็บงาน/Cleaning', categoryRef: 'J', weeksPerHundredSqm: 1, minWeeks: 1, maxWeeks: 2, symbol: '□' },
  ],
  paymentSchedule: [
    { percent: 0.20, label: 'เงินมัดจำ (เริ่มงาน)' },
    { percent: 0.20, label: 'งวดที่ 2 (โครงสร้างเสร็จ)' },
    { percent: 0.30, label: 'งวดที่ 3 (งานระบบ + ตกแต่ง)' },
    { percent: 0.20, label: 'งวดที่ 4 (บิ้วอิน + ภายนอก)' },
    { percent: 0.10, label: 'งวดสุดท้าย (ส่งมอบงาน)' },
  ],
  tags: ['residential', 'new-build'],
};

export const townhouseTemplate: ConstructionTemplate = {
  id: 'townhouse',
  name: 'ทาวน์เฮ้าส์',
  nameEn: 'Townhouse',
  icon: 'Building',
  coverImage: '/images/templates/townhouse.jpg',
  description: 'สร้างทาวน์เฮ้าส์ / ทาวน์โฮม ครบทุกระบบ ไม่รวม Landscape',
  referenceArea: 120,
  minArea: 80,
  maxArea: 250,
  defaultRooms: 3,
  defaultBathrooms: 2,
  categories: [
    designCategory(),
    demolitionCategory(true),
    structureCategory(),
    masonryCategory(),
    electricalCategory(),
    plumbingCategory(),
    bathroomCategory(),
    ceilingCategory(),
    flooringCategory(),
    paintCategory(),
    cleanupCategory(),
    builtInCategory(),
    acCategory(),
  ],
  workPlanPhases: [
    { task: 'ออกแบบ', categoryRef: 'A', weeksPerHundredSqm: 2, minWeeks: 2, maxWeeks: 4, symbol: '■' },
    { task: 'เตรียมพื้นที่/ฐานราก', categoryRef: 'B', weeksPerHundredSqm: 2, minWeeks: 2, maxWeeks: 3, symbol: '□' },
    { task: 'โครงสร้าง', categoryRef: 'M', weeksPerHundredSqm: 5, minWeeks: 4, maxWeeks: 10, symbol: '□' },
    { task: 'ก่อผนัง/ฉาบ', categoryRef: 'C', weeksPerHundredSqm: 2, minWeeks: 2, maxWeeks: 4, symbol: '□' },
    { task: 'ไฟฟ้า', categoryRef: 'D', weeksPerHundredSqm: 1.5, minWeeks: 1, maxWeeks: 3, symbol: '□' },
    { task: 'ประปา', categoryRef: 'E', weeksPerHundredSqm: 1, minWeeks: 1, maxWeeks: 2, symbol: '□' },
    { task: 'ห้องน้ำ', categoryRef: 'F', weeksPerHundredSqm: 2, minWeeks: 2, maxWeeks: 3, symbol: '□' },
    { task: 'ฝ้าเพดาน', categoryRef: 'G', weeksPerHundredSqm: 1.5, minWeeks: 1, maxWeeks: 3, symbol: '□' },
    { task: 'พื้น', categoryRef: 'H', weeksPerHundredSqm: 1, minWeeks: 1, maxWeeks: 2, symbol: '□' },
    { task: 'ทาสี', categoryRef: 'I', weeksPerHundredSqm: 1.5, minWeeks: 1, maxWeeks: 3, symbol: '□' },
    { task: 'บิ้วอิน', categoryRef: 'K', weeksPerHundredSqm: 2, minWeeks: 2, maxWeeks: 4, symbol: '■' },
    { task: 'แอร์', categoryRef: 'L', weeksPerHundredSqm: 0.5, minWeeks: 1, maxWeeks: 1, symbol: '□' },
    { task: 'เก็บงาน/Cleaning', categoryRef: 'J', weeksPerHundredSqm: 1, minWeeks: 1, maxWeeks: 2, symbol: '□' },
  ],
  paymentSchedule: [
    { percent: 0.20, label: 'เงินมัดจำ (เริ่มงาน)' },
    { percent: 0.20, label: 'งวดที่ 2 (โครงสร้างเสร็จ)' },
    { percent: 0.30, label: 'งวดที่ 3 (งานระบบ + ตกแต่ง)' },
    { percent: 0.20, label: 'งวดที่ 4 (บิ้วอิน)' },
    { percent: 0.10, label: 'งวดสุดท้าย (ส่งมอบงาน)' },
  ],
  tags: ['residential', 'new-build'],
};

export const condoRenovationTemplate: ConstructionTemplate = {
  id: 'condo-renovation',
  name: 'คอนโด / รีโนเวทคอนโด',
  nameEn: 'Condo Renovation',
  icon: 'Building2',
  coverImage: '/images/templates/condo.jpg',
  description: 'รีโนเวทคอนโดมิเนียม ตั้งแต่รื้อถอนจนเสร็จสมบูรณ์',
  referenceArea: 50,
  minArea: 25,
  maxArea: 200,
  defaultRooms: 2,
  defaultBathrooms: 1,
  categories: [
    designCategory(),
    demolitionCategory(false),
    masonryCategory(),
    electricalCategory(),
    plumbingCategory(),
    bathroomCategory(),
    ceilingCategory(),
    flooringCategory(),
    paintCategory(),
    cleanupCategory(),
    builtInCategory(),
    acCategory(),
  ],
  workPlanPhases: [
    { task: 'ออกแบบ', categoryRef: 'A', weeksPerHundredSqm: 2, minWeeks: 2, maxWeeks: 4, symbol: '■' },
    { task: 'รื้อถอน', categoryRef: 'B', weeksPerHundredSqm: 1, minWeeks: 1, maxWeeks: 2, symbol: '□' },
    { task: 'ก่อผนัง/ฉาบ', categoryRef: 'C', weeksPerHundredSqm: 2, minWeeks: 1, maxWeeks: 3, symbol: '□' },
    { task: 'ไฟฟ้า', categoryRef: 'D', weeksPerHundredSqm: 1.5, minWeeks: 1, maxWeeks: 2, symbol: '□' },
    { task: 'ประปา', categoryRef: 'E', weeksPerHundredSqm: 1, minWeeks: 1, maxWeeks: 2, symbol: '□' },
    { task: 'ห้องน้ำ', categoryRef: 'F', weeksPerHundredSqm: 2, minWeeks: 1, maxWeeks: 3, symbol: '□' },
    { task: 'ฝ้าเพดาน', categoryRef: 'G', weeksPerHundredSqm: 1.5, minWeeks: 1, maxWeeks: 2, symbol: '□' },
    { task: 'พื้น', categoryRef: 'H', weeksPerHundredSqm: 1, minWeeks: 1, maxWeeks: 2, symbol: '□' },
    { task: 'ทาสี', categoryRef: 'I', weeksPerHundredSqm: 1, minWeeks: 1, maxWeeks: 2, symbol: '□' },
    { task: 'บิ้วอิน', categoryRef: 'K', weeksPerHundredSqm: 3, minWeeks: 2, maxWeeks: 4, symbol: '■' },
    { task: 'แอร์', categoryRef: 'L', weeksPerHundredSqm: 0.5, minWeeks: 1, maxWeeks: 1, symbol: '□' },
    { task: 'เก็บงาน/Cleaning', categoryRef: 'J', weeksPerHundredSqm: 1, minWeeks: 1, maxWeeks: 1, symbol: '□' },
  ],
  paymentSchedule: [
    { percent: 0.30, label: 'เงินมัดจำ (เริ่มงาน)' },
    { percent: 0.30, label: 'งวดที่ 2 (งานระบบ + ฝ้า + พื้น)' },
    { percent: 0.30, label: 'งวดที่ 3 (บิ้วอิน + ทาสี)' },
    { percent: 0.10, label: 'งวดสุดท้าย (ส่งมอบงาน)' },
  ],
  tags: ['residential', 'renovation'],
};

export const commercialTemplate: ConstructionTemplate = {
  id: 'commercial',
  name: 'อาคารพาณิชย์',
  nameEn: 'Commercial Building',
  icon: 'Store',
  coverImage: '/images/templates/commercial.jpg',
  description: 'ก่อสร้าง/ตกแต่งอาคารพาณิชย์ ร้านค้า ออฟฟิศ รวมระบบดับเพลิง',
  referenceArea: 300,
  minArea: 100,
  maxArea: 1000,
  defaultRooms: 4,
  defaultBathrooms: 2,
  categories: [
    designCategory(),
    demolitionCategory(true),
    masonryCategory(),
    electricalCategory(),
    plumbingCategory(),
    bathroomCategory(),
    ceilingCategory(),
    flooringCategory(),
    paintCategory(),
    cleanupCategory(),
    builtInCategory(),
    acCategory(),
    facadeCategory(),
    fireProtectionCategory(),
  ],
  workPlanPhases: [
    { task: 'ออกแบบ', categoryRef: 'A', weeksPerHundredSqm: 3, minWeeks: 3, maxWeeks: 6, symbol: '■' },
    { task: 'เตรียมพื้นที่', categoryRef: 'B', weeksPerHundredSqm: 2, minWeeks: 2, maxWeeks: 4, symbol: '□' },
    { task: 'ก่อผนัง/ฉาบ', categoryRef: 'C', weeksPerHundredSqm: 3, minWeeks: 2, maxWeeks: 6, symbol: '□' },
    { task: 'ไฟฟ้า', categoryRef: 'D', weeksPerHundredSqm: 2, minWeeks: 2, maxWeeks: 4, symbol: '□' },
    { task: 'ประปา', categoryRef: 'E', weeksPerHundredSqm: 1.5, minWeeks: 1, maxWeeks: 3, symbol: '□' },
    { task: 'ห้องน้ำ', categoryRef: 'F', weeksPerHundredSqm: 2, minWeeks: 2, maxWeeks: 3, symbol: '□' },
    { task: 'ฝ้าเพดาน', categoryRef: 'G', weeksPerHundredSqm: 2, minWeeks: 1, maxWeeks: 4, symbol: '□' },
    { task: 'พื้น', categoryRef: 'H', weeksPerHundredSqm: 1.5, minWeeks: 1, maxWeeks: 3, symbol: '□' },
    { task: 'ทาสี', categoryRef: 'I', weeksPerHundredSqm: 2, minWeeks: 1, maxWeeks: 4, symbol: '□' },
    { task: 'Facade/ป้าย', categoryRef: 'M', weeksPerHundredSqm: 3, minWeeks: 2, maxWeeks: 6, symbol: '□' },
    { task: 'ระบบดับเพลิง', categoryRef: 'N', weeksPerHundredSqm: 1, minWeeks: 1, maxWeeks: 2, symbol: '□' },
    { task: 'บิ้วอิน', categoryRef: 'K', weeksPerHundredSqm: 3, minWeeks: 2, maxWeeks: 6, symbol: '■' },
    { task: 'แอร์', categoryRef: 'L', weeksPerHundredSqm: 1, minWeeks: 1, maxWeeks: 2, symbol: '□' },
    { task: 'เก็บงาน/Cleaning', categoryRef: 'J', weeksPerHundredSqm: 1, minWeeks: 1, maxWeeks: 2, symbol: '□' },
  ],
  paymentSchedule: [
    { percent: 0.20, label: 'เงินมัดจำ (เริ่มงาน)' },
    { percent: 0.20, label: 'งวดที่ 2 (งานระบบเสร็จ)' },
    { percent: 0.25, label: 'งวดที่ 3 (ตกแต่งภายใน)' },
    { percent: 0.25, label: 'งวดที่ 4 (Facade + บิ้วอิน)' },
    { percent: 0.10, label: 'งวดสุดท้าย (ส่งมอบงาน)' },
  ],
  tags: ['commercial', 'new-build'],
};

export const renovationTemplate: ConstructionTemplate = {
  id: 'renovation',
  name: 'รีโนเวท (ทั่วไป)',
  nameEn: 'General Renovation',
  icon: 'Hammer',
  coverImage: '/images/templates/renovate.jpg',
  description: 'รีโนเวทบ้าน/อาคาร ปรับปรุงพื้นที่เดิม ไม่รวมค่าออกแบบ',
  referenceArea: 100,
  minArea: 30,
  maxArea: 500,
  defaultRooms: 2,
  defaultBathrooms: 1,
  categories: [
    demolitionCategory(false),
    masonryCategory(),
    electricalCategory(),
    plumbingCategory(),
    bathroomCategory(),
    ceilingCategory(),
    flooringCategory(),
    paintCategory(),
    cleanupCategory(),
    builtInCategory(),
    acCategory(),
  ],
  workPlanPhases: [
    { task: 'รื้อถอน', categoryRef: 'B', weeksPerHundredSqm: 1, minWeeks: 1, maxWeeks: 2, symbol: '□' },
    { task: 'ก่อผนัง/ฉาบ', categoryRef: 'C', weeksPerHundredSqm: 2, minWeeks: 1, maxWeeks: 4, symbol: '□' },
    { task: 'ไฟฟ้า', categoryRef: 'D', weeksPerHundredSqm: 1.5, minWeeks: 1, maxWeeks: 3, symbol: '□' },
    { task: 'ประปา', categoryRef: 'E', weeksPerHundredSqm: 1, minWeeks: 1, maxWeeks: 2, symbol: '□' },
    { task: 'ห้องน้ำ', categoryRef: 'F', weeksPerHundredSqm: 2, minWeeks: 1, maxWeeks: 3, symbol: '□' },
    { task: 'ฝ้าเพดาน', categoryRef: 'G', weeksPerHundredSqm: 1.5, minWeeks: 1, maxWeeks: 3, symbol: '□' },
    { task: 'พื้น', categoryRef: 'H', weeksPerHundredSqm: 1, minWeeks: 1, maxWeeks: 2, symbol: '□' },
    { task: 'ทาสี', categoryRef: 'I', weeksPerHundredSqm: 1.5, minWeeks: 1, maxWeeks: 3, symbol: '□' },
    { task: 'บิ้วอิน', categoryRef: 'K', weeksPerHundredSqm: 2, minWeeks: 2, maxWeeks: 4, symbol: '■' },
    { task: 'แอร์', categoryRef: 'L', weeksPerHundredSqm: 0.5, minWeeks: 1, maxWeeks: 1, symbol: '□' },
    { task: 'เก็บงาน/Cleaning', categoryRef: 'J', weeksPerHundredSqm: 1, minWeeks: 1, maxWeeks: 1, symbol: '□' },
  ],
  paymentSchedule: [
    { percent: 0.30, label: 'เงินมัดจำ (เริ่มงาน)' },
    { percent: 0.30, label: 'งวดที่ 2 (งานระบบ + ฝ้า + พื้น)' },
    { percent: 0.30, label: 'งวดที่ 3 (บิ้วอิน + ทาสี)' },
    { percent: 0.10, label: 'งวดสุดท้าย (ส่งมอบงาน)' },
  ],
  tags: ['residential', 'renovation'],
};

export const officeFitoutTemplate: ConstructionTemplate = {
  id: 'office-fitout',
  name: 'ตกแต่งสำนักงาน',
  nameEn: 'Office Fit-out',
  icon: 'Briefcase',
  coverImage: '/images/templates/office.jpg',
  description: 'ตกแต่งสำนักงาน/ออฟฟิศ รวมพาร์ทิชั่น ระบบ IT และแอร์',
  referenceArea: 150,
  minArea: 50,
  maxArea: 500,
  defaultRooms: 4,
  defaultBathrooms: 1,
  categories: [
    designCategory(),
    demolitionCategory(false),
    masonryCategory(),
    electricalCategory(),
    plumbingCategory(),
    bathroomCategory(),
    ceilingCategory(),
    flooringCategory(),
    paintCategory(),
    cleanupCategory(),
    builtInCategory(),
    acCategory(),
    partitionCategory(),
    itCategory(),
  ],
  workPlanPhases: [
    { task: 'ออกแบบ', categoryRef: 'A', weeksPerHundredSqm: 2, minWeeks: 2, maxWeeks: 4, symbol: '■' },
    { task: 'รื้อถอน', categoryRef: 'B', weeksPerHundredSqm: 1, minWeeks: 1, maxWeeks: 2, symbol: '□' },
    { task: 'ก่อผนัง/ฉาบ', categoryRef: 'C', weeksPerHundredSqm: 1.5, minWeeks: 1, maxWeeks: 3, symbol: '□' },
    { task: 'ไฟฟ้า', categoryRef: 'D', weeksPerHundredSqm: 1.5, minWeeks: 1, maxWeeks: 3, symbol: '□' },
    { task: 'ประปา', categoryRef: 'E', weeksPerHundredSqm: 1, minWeeks: 1, maxWeeks: 2, symbol: '□' },
    { task: 'พาร์ทิชั่น/กระจก', categoryRef: 'M', weeksPerHundredSqm: 2, minWeeks: 1, maxWeeks: 3, symbol: '□' },
    { task: 'ฝ้าเพดาน', categoryRef: 'G', weeksPerHundredSqm: 1.5, minWeeks: 1, maxWeeks: 2, symbol: '□' },
    { task: 'พื้น', categoryRef: 'H', weeksPerHundredSqm: 1, minWeeks: 1, maxWeeks: 2, symbol: '□' },
    { task: 'ทาสี', categoryRef: 'I', weeksPerHundredSqm: 1, minWeeks: 1, maxWeeks: 2, symbol: '□' },
    { task: 'IT/LAN/CCTV', categoryRef: 'N', weeksPerHundredSqm: 1, minWeeks: 1, maxWeeks: 2, symbol: '□' },
    { task: 'บิ้วอิน', categoryRef: 'K', weeksPerHundredSqm: 2, minWeeks: 2, maxWeeks: 4, symbol: '■' },
    { task: 'แอร์', categoryRef: 'L', weeksPerHundredSqm: 1, minWeeks: 1, maxWeeks: 2, symbol: '□' },
    { task: 'เก็บงาน/Cleaning', categoryRef: 'J', weeksPerHundredSqm: 1, minWeeks: 1, maxWeeks: 1, symbol: '□' },
  ],
  paymentSchedule: [
    { percent: 0.30, label: 'เงินมัดจำ (เริ่มงาน)' },
    { percent: 0.25, label: 'งวดที่ 2 (งานระบบ + พาร์ทิชั่น)' },
    { percent: 0.25, label: 'งวดที่ 3 (ตกแต่ง + บิ้วอิน)' },
    { percent: 0.10, label: 'งวดที่ 4 (IT + แอร์)' },
    { percent: 0.10, label: 'งวดสุดท้าย (ส่งมอบงาน)' },
  ],
  tags: ['commercial', 'fitout'],
};

export const vanavardInteriorTemplate: ConstructionTemplate = {
  id: 'vanavard-interior',
  name: 'Vanavard Interior',
  nameEn: 'Vanavard Interior',
  icon: 'Sparkles',
  coverImage: '/images/templates/vanavard.jpg',
  description: 'Template สำหรับงาน interior ของ Vanavard: ค่าออกแบบ 1,000 บาท/ตร.ม. + งานบิ้วอินและงานตกแต่งหลัก พร้อมส่วนลดอัตโนมัติเมื่อมีงานบิ้วอิน',
  referenceArea: 60,
  minArea: 10,
  maxArea: 250,
  defaultRooms: 2,
  defaultBathrooms: 1,
  categories: [
    vanavardInteriorDesignCategory(),
    demolitionCategory(false),
    masonryCategory(),
    electricalCategory(),
    plumbingCategory(),
    bathroomCategory(),
    ceilingCategory(),
    flooringCategory(),
    paintCategory(),
    cleanupCategory(),
    builtInCategory(),
    acCategory(),
  ],
  workPlanPhases: [
    { task: 'ออกแบบ + สรุป BOQ', categoryRef: 'A', weeksPerHundredSqm: 2, minWeeks: 1, maxWeeks: 4, symbol: '■' },
    { task: 'รื้อถอน / เตรียมพื้นที่', categoryRef: 'B', weeksPerHundredSqm: 1.5, minWeeks: 1, maxWeeks: 3, symbol: '□' },
    { task: 'ก่อผนัง / ปรับพื้นที่', categoryRef: 'C', weeksPerHundredSqm: 1.5, minWeeks: 1, maxWeeks: 3, symbol: '□' },
    { task: 'งานระบบไฟฟ้า', categoryRef: 'D', weeksPerHundredSqm: 1.5, minWeeks: 1, maxWeeks: 3, symbol: '□' },
    { task: 'งานระบบประปา', categoryRef: 'E', weeksPerHundredSqm: 1, minWeeks: 1, maxWeeks: 2, symbol: '□' },
    { task: 'งานห้องน้ำ', categoryRef: 'F', weeksPerHundredSqm: 1.5, minWeeks: 1, maxWeeks: 3, symbol: '□' },
    { task: 'ฝ้า / พื้น / สี', categoryRef: 'G', weeksPerHundredSqm: 2, minWeeks: 1, maxWeeks: 4, symbol: '□' },
    { task: 'งานบิ้วอิน', categoryRef: 'K', weeksPerHundredSqm: 2, minWeeks: 2, maxWeeks: 5, symbol: '■' },
    { task: 'ติดตั้งแอร์ / เก็บงาน', categoryRef: 'L', weeksPerHundredSqm: 1, minWeeks: 1, maxWeeks: 2, symbol: '□' },
    { task: 'ตรวจรับ + Cleaning', categoryRef: 'J', weeksPerHundredSqm: 1, minWeeks: 1, maxWeeks: 2, symbol: '□' },
  ],
  paymentSchedule: [
    { percent: 0.40, label: 'งวดที่ 1 (ยืนยันแบบ + เริ่มผลิต/สั่งของ)' },
    { percent: 0.30, label: 'งวดที่ 2 (เริ่มติดตั้งหน้างาน)' },
    { percent: 0.30, label: 'งวดที่ 3 (ส่งมอบงาน)' },
  ],
  tags: ['vanavard', 'interior', 'builtin'],
  defaultMarkupRate: 0.25,
  defaultOperatingRate: 0,
  defaultDiscountConfig: {
    label: 'ส่วนลดค่าออกแบบ 25% (เมื่อทำบิ้วอินกับบริษัท)',
    percent: 0.25,
    appliesToCategoryRefs: ['A'],
    requiresCategoryRefs: ['K'],
    condition: 'ส่วนลดนี้ใช้เมื่อผู้ว่าจ้างตกลงทำงานบิ้วอินกับบริษัท หากยกเลิกงานบิ้วอิน บริษัทขอสงวนสิทธิ์เรียกเก็บส่วนลดคืนตามมูลค่าที่ลดให้',
  },
};

// Registry ของ templates ทั้งหมด
export const constructionTemplates: ConstructionTemplate[] = [
  singleHouseTemplate,
  townhouseTemplate,
  condoRenovationTemplate,
  commercialTemplate,
  renovationTemplate,
  officeFitoutTemplate,
  vanavardInteriorTemplate,
];

export function getTemplateById(id: string): ConstructionTemplate | undefined {
  return constructionTemplates.find((t) => t.id === id);
}
