import { ProjectData } from './projectData';

export const phase5Project: ProjectData = {
  id: 'phase5-final-finishing',
  name: 'Phase 5 - งานสี เก็บงาน ส่งมอบ',
  address: 'คอนโดวิลล่าราชเทวี',
  phone: '-',
  owner: '-',
  quotationData: [
    {
      no: 'I',
      description: 'งานสีผนังและเก็บผิว (Painting & Surface Finishing)',
      unit: '',
      quantity: '',
      unitPrice: '',
      laborCost: '',
      scopeDetails: '• เก็บผิวงานผนังและรอยต่อ\n• รองพื้นก่อนทาสีจริง\n• ทาสีเก็บรายละเอียดรอบสุดท้าย',
    },
    {
      no: 'I.1',
      description: 'รองพื้น + อุดโป๊ว + ขัดเก็บผิว',
      unit: 'ตร.ม.',
      quantity: 200,
      unitPrice: 0,
      laborCost: 60,
      scopeDetails: '• รองพื้นผนัง\n• โป๊วรอยแตกร้าว\n• อุดรอยบกพร่อง\n• ขัดให้เรียบ',
    },
    {
      no: 'I.2',
      description: 'ทาสี 2-3 รอบ',
      unit: 'ตร.ม.',
      quantity: 200,
      unitPrice: 0,
      laborCost: 70,
      scopeDetails: '• ทาสีผนังภายใน\n• สี TOA/Beger คุณภาพดี\n• ทา 2-3 รอบ หรือจนปกปิด\n• เก็บผิวเรียบสวย',
    },
    {
      no: 'J',
      description: 'งานเก็บงาน / Defect / Big Cleaning (Final Handover)',
      unit: '',
      quantity: '',
      unitPrice: '',
      laborCost: '',
      scopeDetails: '• เก็บงานละเอียดก่อนส่งมอบ\n• แก้ไขข้อบกพร่อง 2 รอบ\n• ทำความสะอาดใหญ่ก่อนลูกค้าเข้าใช้งาน',
    },
    {
      no: 'J.1',
      description: 'Big Cleaning',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 8000,
      scopeDetails: '• ทำความสะอาดใหญ่ทั้งห้อง\n• ดูดฝุ่น ถูพื้น\n• เช็ดกระจก/ผนัง/เฟอร์\n• เก็บเศษวัสดุละเอียด',
    },
    {
      no: 'J.2',
      description: 'Defect 2 รอบ',
      unit: 'รอบ',
      quantity: 2,
      unitPrice: 0,
      laborCost: 3000,
      scopeDetails: '• ตรวจสอบข้อบกพร่อง\n• แก้ไขจุดที่ต้องปรับปรุง\n• รอบที่ 1: หลังเสร็จงานหลัก\n• รอบที่ 2: ก่อนส่งมอบ',
    },
  ],
};
