import { ProjectData } from './projectData';

export const phase3Project: ProjectData = {
  id: 'phase3-electrical-ceiling-plumbing',
  name: 'Phase 3 - งานไฟ ฝ้า ประปา',
  address: 'คอนโดวิลล่าราชเทวี',
  phone: '-',
  owner: '-',
  quotationData: [
    // E) งานระบบไฟฟ้า
    {
      no: 'E',
      description: 'งานระบบไฟฟ้า (Electrical System)',
      unit: '',
      quantity: '',
      unitPrice: '',
      laborCost: '',
    },
    {
      no: 'E.1',
      description: 'เดินท่อร้อยสายไฟแสงสว่าง ขนาดสายเบอร์ 1.5 L/N',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 14000,
    },
    {
      no: 'E.2',
      description: 'เดินท่อร้อยสายไฟ ปลั๊กไฟ ขนาดสายเบอร์ 2.5 L/N 1.5 G',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 18000,
    },
    {
      no: 'E.3',
      description: 'เดินท่อร้อยสายไฟ สวิตช์ไฟ (นับตามบ๊อก)',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 6500,
    },
    {
      no: 'E.4',
      description: 'เดินสายติดไฟ LED หัวเตียง ห้องนอน 1',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 1200,
    },
    {
      no: 'E.5',
      description: 'เดินสายติดไฟ LED ตู้เสื้อผ้า + สวิตช์เซ็นเซอร์ ห้องนอน 1',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 1800,
    },
    {
      no: 'E.6',
      description: 'เดินสายติดไฟ LED ฝ้าเพดานห้องนอน 1',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 1000,
    },
    {
      no: 'E.7',
      description: 'เดินสายติดไฟ LED ชั้นวางของข้างกระจก ห้องนอน 1',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 1200,
    },
    {
      no: 'E.8',
      description: 'เดินสายติดไฟ LED ตู้เสื้อผ้า หน้าห้องน้ำ ห้องนอน 1',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 1800,
    },
    {
      no: 'E.9',
      description: 'เดินสายติดไฟ LED ห้องน้ำ',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 1100,
    },
    {
      no: 'E.10',
      description: 'เดินสายติดไฟ LED ครัว',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 1100,
    },
    {
      no: 'E.11',
      description: 'เดินสายติดไฟ LED ใต้เคาน์เตอร์หน้าห้องครัว',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 1000,
    },
    {
      no: 'E.12',
      description: 'เดินสายติดไฟ LED บนงานบิ้ว ห้องนอน 2',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 1000,
    },
    {
      no: 'E.13',
      description: 'เดินสายติดไฟ LED บนฝ้าห้องนอน 2',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 1000,
    },
    {
      no: 'E.14',
      description: 'เดินสายติดไฟ LED โถงนั่งเล่นบนฝ้าทั้งหมด',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 3000,
    },
    {
      no: 'E.15',
      description: 'เดินสายติดไฟห้อยโถงนั่งเล่น',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 1600,
    },
    {
      no: 'E.16',
      description: 'เดินสายติดไฟแทรกไลท์ ห้องโถงนั่งเล่นทั้งหมด',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 4700,
    },
    {
      no: 'E.17',
      description: 'เดินสายติดไฟแทรกไลท์ ห้องนอน 2',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 1200,
    },
    {
      no: 'E.18',
      description: 'เดินสายไฟ 2 ทาง หัวเตียง',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 800,
    },
    {
      no: 'E.19',
      description: 'เดินท่อร้อยสาย เครื่องซัก+เครื่องอบแห้ง (แยก 1 เซอร์กิต) ขนาดสายเบอร์ 4 L/N 2.5 G',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 2900,
    },
    {
      no: 'E.20',
      description: 'เดินท่อร้อยสายไฟ เตาไฟ+ฮูด (แยกเซอร์กิต) ขนาดสายเบอร์ 6 L/N 2.5 G',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 3600,
    },
    {
      no: 'E.21',
      description: 'เดินท่อร้อยสายไฟ ไมโครเวฟ+ปลั๊ก+FOR REF (รวมเซอร์กิตเดียวกัน) ขนาดสายเบอร์ 4 L/N 2.5 G',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 2900,
    },
    {
      no: 'E.22',
      description: 'เดินท่อร้อยสายไฟ เครื่องน้ำอุ่น ขนาดสายเบอร์ 4 L/N 2.5 G + ลูกเซอร์กิตกันดูด',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 3700,
    },
    {
      no: 'E.23',
      description: 'เดินท่อร้อยสายเมนแอร์ ขนาดสาย 2.5 LN 1.5 G',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 3600,
    },
    {
      no: 'E.24',
      description: 'เดินท่อร้อยสายแลน CAT6',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 3000,
    },
    {
      no: 'E.25',
      description: 'เดินท่อร้อยสาย TV',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 1400,
    },
    {
      no: 'E.26',
      description: 'เข้าตู้ไฟเก็บสายใหม่',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 1500,
    },
    {
      no: 'E.27',
      description: 'สวิตช์ดิมเมอร์ ห้องนอน',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 800,
      scopeDetails: '*** หมายเหตุ ***\n• ใช้ท่อ PVC ขาว\n• ใช้สวิตช์ปลั๊ก พานาโซนิคสีขาว\n• ใช้สาย ยี่ห้อ YAZAKI\n• ไม่รวมอุปกรณ์โคมไฟ\n\n*** รวมค่าวัสดุและค่าแรงแล้ว ***',
    },

    // F) งานฝ้า
    {
      no: 'F',
      description: 'งานฝ้า (Ceiling System)',
      unit: '',
      quantity: '',
      unitPrice: '',
      laborCost: '',
    },
    {
      no: 'F.1',
      description: 'งานฝ้าฉาบเรียบห้องนั่งเล่น โครง SCG แผ่นธรรมดาตราช้าง 9 มม.',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 33515,
    },
    {
      no: 'F.2',
      description: 'งานฝ้าห้องน้ำ โครง SCG แผ่นทนชื้นตราช้าง 9 มม.',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 6500,
    },
    {
      no: 'F.3',
      description: 'งานสเต็ปฝ้ารางม่าน',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 7548,
    },
    {
      no: 'F.4',
      description: 'งานฝ้าระเบียงด้านนอก แผ่นยิปซั่มทนชื้น 9 มม.',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 6000,
      scopeDetails: '*** หมายเหตุ ***\n• ใช้โครงฝ้า SCG คุณภาพดี\n• แผ่นยิปซั่มตราช้าง\n• งานฉาบเรียบพร้อมทาสีรองพื้น\n\n*** รวมค่าวัสดุและค่าแรงแล้ว ***',
    },
    {
      no: 'F.5',
      description: 'งานทาสีฝ้า TOA สีขาว รหัส A8000',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 19174,
      scopeDetails: '• พื้นที่รวม 95.87 ตร.ม. (ห้องนั่งเล่น 67 + ห้องน้ำ 10 + สเต็ปฝ้า 18.87)\n• ราคา 250 บาท/ตร.ม.\n• สีทาฝ้า TOA สีขาว รหัส A8000\n• ทา 2 ชั้น\n\n*** รวมค่าวัสดุและค่าแรงแล้ว ***',
    },

    // G) งานเดินท่อ PVC + PPE
    {
      no: 'G',
      description: 'งานระบบประปา (Plumbing System)',
      unit: '',
      quantity: '',
      unitPrice: '',
      laborCost: '',
    },
    {
      no: 'G.1',
      description: 'เดินท่อ PVC ใหม่ทั้งหมด และท่อ PPE น้ำร้อน',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 13000,
      scopeDetails: '• เดินท่อ PVC น้ำประปาใหม่ทั้งระบบ\n• เดินท่อ PPE น้ำร้อนตามจุดต่างๆ\n• ข้อต่อและอุปกรณ์ประกอบครบชุด\n• ทดสอบความรั่วซึมของระบบ\n\n*** รวมค่าวัสดุและค่าแรงแล้ว ***',
    },
  ],
};
