import { ProjectData } from './projectData';

export const phase4Project: ProjectData = {
  id: 'phase4-builtin-furniture',
  name: 'Phase 4 - งานบิ้วอิน (Built-in Furniture)',
  address: 'คอนโดวิลล่าราชเทวี',
  phone: '-',
  owner: '-',
  quotationData: [
    // H) งานบิ้วอินเฟอร์นิเจอร์
    {
      no: 'H',
      description: 'งานบิ้วอินเฟอร์นิเจอร์ (Built-in Furniture)',
      unit: '',
      quantity: '',
      unitPrice: '',
      laborCost: '',
    },
    {
      no: 'H.1',
      description: 'SHOE CABINET & STORAGE (ตู้รองเท้าและตู้เก็บของ)',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: '-',
      laborCost: '-',
      totalPrice: 32143,
    },
    {
      no: 'H.2',
      description: 'COUNTER PANTRY (เคาน์เตอร์แพนทรี) - ชุดที่ 1',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: '-',
      laborCost: '-',
      totalPrice: 32143,
    },
    {
      no: 'H.3',
      description: 'COUNTER PANTRY (เคาน์เตอร์แพนทรี) - ชุดที่ 2',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: '-',
      laborCost: '-',
      totalPrice: 32143,
    },
    {
      no: 'H.4',
      description: 'STORAGE (ตู้เก็บของ) - ชุดที่ 1',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: '-',
      laborCost: '-',
      totalPrice: 32143,
    },
    {
      no: 'H.5',
      description: 'TV. CABINET (ตู้วางทีวี)',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: '-',
      laborCost: '-',
      totalPrice: 32143,
    },
    {
      no: 'H.6',
      description: 'STORAGE (ตู้เก็บของ) - ชุดที่ 2',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: '-',
      laborCost: '-',
      totalPrice: 32143,
    },
    {
      no: 'H.7',
      description: 'WALL DECORATE & SIDE TABLE (ผนังตกแต่งและโต๊ะข้าง)',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: '-',
      laborCost: '-',
      totalPrice: 32143,
    },
    {
      no: 'H.8',
      description: 'CLOSET (ตู้เสื้อผ้า) - ชุดที่ 1',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: '-',
      laborCost: '-',
      totalPrice: 32143,
    },
    {
      no: 'H.9',
      description: 'DRESSING TABLE (โต๊ะเครื่องแป้ง)',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: '-',
      laborCost: '-',
      totalPrice: 32143,
    },
    {
      no: 'H.10',
      description: 'BENCH (ม้านั่งยาว)',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: '-',
      laborCost: '-',
      totalPrice: 32143,
    },
    {
      no: 'H.11',
      description: 'CLOSET (ตู้เสื้อผ้า) - ชุดที่ 2',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: '-',
      laborCost: '-',
      totalPrice: 32143,
    },
    {
      no: 'H.12',
      description: 'WALL DECORATE & BED (ผนังตกแต่งและเตียงนอน)',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: '-',
      laborCost: '-',
      totalPrice: 32143,
    },
    {
      no: 'H.13',
      description: 'CLOSET (ตู้เสื้อผ้า) - ชุดที่ 3',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: '-',
      laborCost: '-',
      totalPrice: 32143,
    },
    {
      no: 'H.14',
      description: 'CABINET & STORAGE (ตู้เก็บของ)',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: '-',
      laborCost: '-',
      totalPrice: 32141, // ปรับให้รวมพอดี 450,000
    },
  ],
  scopeDetails: '*** รายละเอียดงานบิ้วอิน ***\n• วัสดุหน้าบาน: Laminate\n• โครงตู้: HMR\n• บานพับ: Hafele\n• รางลิ้นชัก: Soft-Close Hafele\n• ติดตั้งครบชุดพร้อมใช้งาน\n\n*** หมายเหตุ ราคานี้ไม่รวมแผ่น Laminate ***',
  designFee: 0, // ไม่มีค่าออกแบบ
  totalCost: 450000, // ราคาทุนตายตัว
  customerPrice: 600000, // ราคาลูกค้าตายตัว (ไม่บวกกำไร)
  operatingCost: 0, // ไม่มีค่าดำเนินการ
};
