import { ProjectData } from './projectData';

export const villaRatchathewi2BR: ProjectData = {
  id: 'villa-ratchathewi-2br-room175',
  name: 'VILLA Ratchathewi (2BR ROOM 175)',
  address: 'คอนโด VILLA Ratchathewi, ห้อง 175 (2 ห้องนอน)',
  phone: '',
  owner: '',
  quotationData: [
    // A) ค่าออกแบบ / แบบก่อสร้าง
    {
      no: 'A',
      description: 'ค่าออกแบบ / แบบก่อสร้าง',
      unit: '-',
      quantity: '',
      unitPrice: '',
      laborCost: '',
    },
    {
      no: 'A1',
      description: 'ค่าออกแบบ + จัดทำแบบก่อสร้าง',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 25000,
      laborCost: 0,
      scopeDetails: '- ออกแบบรีโนเวทคอนโด 2 ห้องนอน\n- จัดทำแบบก่อสร้างครบชุด\n- แบบ layout, แบบไฟฟ้า, แบบประปา\n- Final Design (ราคาสุดท้าย)',
    },

    // 1) งานเตรียมการและป้องกันหน้างาน
    {
      no: '1',
      description: 'งานเตรียมการและป้องกันหน้างาน (Site Prep)',
      unit: '-',
      quantity: '',
      unitPrice: '',
      laborCost: '',
    },
    {
      no: '1.1',
      description: 'ปูพื้น/คลุมผนัง/คลุมเฟอร์ฯที่คงไว้ + เทปกันกระแทก',
      unit: 'รายการ',
      quantity: '',
      unitPrice: '',
      laborCost: '',
      scopeDetails: 'Included ในหมวด 2.0 (เหมารื้อทิ้งทั้งหมด)\n\n- ปูพลาสติกคลุมพื้น\n- คลุมผนังและเฟอร์นิเจอร์ที่คงไว้\n- ติดเทปกันกระแทกตามจุดเสี่ยง\n- ป้องกันความเสียหายระหว่างก่อสร้าง',
    },
    {
      no: '1.2',
      description: 'ถอด/ย้ายของเดิม + แพ็กเก็บ (ถ้ามี)',
      unit: 'รายการ',
      quantity: '',
      unitPrice: '',
      laborCost: '',
      scopeDetails: 'Included ในหมวด 2.0 (เหมารื้อทิ้งทั้งหมด)\n\n- ถอดและย้ายของใช้เดิม\n- แพ็กเก็บอย่างปลอดภัย\n- จัดเก็บในพื้นที่ที่กำหนด',
    },
    {
      no: '1.4',
      description: 'ขนทิ้งเศษวัสดุ',
      unit: 'รายการ',
      quantity: '',
      unitPrice: '',
      laborCost: '',
      scopeDetails: 'Included ในหมวด 2.0 (เหมารื้อทิ้งทั้งหมด)\n\n- ขนเศษวัสดุออกจากหน้างาน\n- ทิ้งตามสถานที่ที่กำหนด\n- รวมค่าทิ้งขยะ',
    },

    // 2) งานรื้อถอน
    {
      no: '2',
      description: 'งานรื้อถอน (Demolition) "รื้อทิ้งทั้งหมด"',
      unit: '-',
      quantity: '',
      unitPrice: '',
      laborCost: '',
    },
    {
      no: '2.0',
      description: 'เหมางานรื้อทิ้งทั้งหมด + ขนทิ้ง (รวม 2.1-2.9 และ 8.1)',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 55000,
      laborCost: 0,
      scopeDetails: '- รื้อบิ้วอินทั้งหมด + ขนลง\n- ทุบผนังตามแบบ + ขนทิ้ง\n- ถอดแอร์เก่าออกทั้งหมด (ไม่รวมติดตั้งใหม่)\n- รื้อฝ้าเก่าทั้งหมด + ขนทิ้ง\n- รื้อพื้นเดิมทั้งหมด + ขนทิ้ง\n- รื้อชุดครัวเดิม/ซิงก์/ท่อน้ำทิ้งเดิม\n- รื้อสุขภัณฑ์เดิม/ฉากกั้น/อุปกรณ์ห้องน้ำเดิม\n- รื้อวงกบ/บานประตู/อุปกรณ์เดิม (ถ้าเปลี่ยน)\n- สกัดกระเบื้องพื้น+ผนังห้องน้ำทั้งหมด\n\n*** ราคาเหมาครอบคลุมทั้งหมด (Final) ***',
    },
    {
      no: '2.1',
      description: 'รื้อบิ้วอินทั้งหมด + ขนลง',
      unit: 'รายการ',
      quantity: '',
      unitPrice: '',
      laborCost: '',
      scopeDetails: 'Included ในหมวด 2.0',
    },
    {
      no: '2.2',
      description: 'ทุบผนังตามแบบ + ขนทิ้ง',
      unit: 'รายการ',
      quantity: '',
      unitPrice: '',
      laborCost: '',
      scopeDetails: 'Included ในหมวด 2.0',
    },
    {
      no: '2.3',
      description: 'ถอดแอร์เก่าออกทั้งหมด (ไม่รวมติดตั้งใหม่)',
      unit: 'รายการ',
      quantity: '',
      unitPrice: '',
      laborCost: '',
      scopeDetails: 'Included ในหมวด 2.0',
    },
    {
      no: '2.4',
      description: 'รื้อฝ้าเก่าทั้งหมด + ขนทิ้ง',
      unit: 'รายการ',
      quantity: '',
      unitPrice: '',
      laborCost: '',
      scopeDetails: 'Included ในหมวด 2.0',
    },
    {
      no: '2.5',
      description: 'รื้อพื้นเดิมทั้งหมด + ขนทิ้ง',
      unit: 'รายการ',
      quantity: '',
      unitPrice: '',
      laborCost: '',
      scopeDetails: 'Included ในหมวด 2.0',
    },
    {
      no: '2.6',
      description: 'รื้อชุดครัวเดิม/ซิงก์/ท่อน้ำทิ้งเดิม',
      unit: 'รายการ',
      quantity: '',
      unitPrice: '',
      laborCost: '',
      scopeDetails: 'Included ในหมวด 2.0',
    },
    {
      no: '2.7',
      description: 'รื้อสุขภัณฑ์เดิม/ฉากกั้น/อุปกรณ์ห้องน้ำเดิม',
      unit: 'รายการ',
      quantity: '',
      unitPrice: '',
      laborCost: '',
      scopeDetails: 'Included ในหมวด 2.0',
    },
    {
      no: '2.8',
      description: 'รื้อวงกบ/บานประตู/อุปกรณ์เดิม (ถ้าเปลี่ยน)',
      unit: 'รายการ',
      quantity: '',
      unitPrice: '',
      laborCost: '',
      scopeDetails: 'Included ในหมวด 2.0',
    },
    {
      no: '2.9',
      description: 'สกัดกระเบื้องพื้น+ผนังห้องน้ำทั้งหมด',
      unit: 'รายการ',
      quantity: '',
      unitPrice: '',
      laborCost: '',
      scopeDetails: 'Included ในหมวด 2.0',
    },

    // 3) งานโครงสร้าง/ก่อผนัง/งานปิดผิว
    {
      no: '3',
      description: 'งานโครงสร้าง/ก่อผนัง/งานปิดผิว (Masonry & Wall) — รอแบบก่อสร้าง (TBD)',
      unit: '-',
      quantity: '',
      unitPrice: '',
      laborCost: '',
    },
    {
      no: '3.1',
      description: 'ก่อผนังใหม่/ปิดช่อง/แก้ layout ตามแบบ',
      unit: 'ตร.ม.',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- ก่อผนังอิฐมวลเบา/บล็อก\n- ปิดช่องเดิมตามแบบ\n- ปรับ layout ห้อง\n- TBD: รอแบบก่อสร้าง',
    },
    {
      no: '3.2',
      description: 'ฉาบเรียบ/เก็บผิว/เข้ามุม',
      unit: 'ตร.ม.',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- ฉาบปูนเรียบ\n- เก็บมุม 90 องศา\n- เตรียมผิวก่อนทาสี\n- TBD: รอแบบก่อสร้าง',
    },
    {
      no: '3.3',
      description: 'โป๊ว-ขัด-เตรียมผนังก่อนทาสี (ทั้งห้อง)',
      unit: 'ตร.ม.',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- โป๊วผนังทั้งหมด\n- ขัดให้เรียบ\n- รองพื้นก่อนทาสี\n- TBD: รอแบบก่อสร้าง',
    },
    {
      no: '3.4',
      description: 'เจาะ/ทำช่องเซอร์วิส/ฝาปิดงานระบบ (ใต้ซิงก์/ตู้บาน ฯลฯ)',
      unit: 'จุด',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- เจาะช่องสำหรับท่อประปา\n- ช่องไฟฟ้า\n- ฝาปิดบำรุงรักษา\n- TBD: รอแบบก่อสร้าง',
    },

    // 4) งานระบบไฟฟ้า
    {
      no: '4',
      description: 'งานระบบไฟฟ้า (Electrical) "เดินใหม่หมด" — รอแบบก่อสร้าง (TBD)',
      unit: '-',
      quantity: '',
      unitPrice: '',
      laborCost: '',
    },
    {
      no: '4.1',
      description: 'รื้อสายไฟ/สวิตช์/ปลั๊ก/เบรกเกอร์เดิมที่ไม่ใช้',
      unit: 'งาน',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- รื้อสายไฟเก่า\n- ถอดสวิตช์และปลั๊กเดิม\n- TBD: รอแบบก่อสร้าง',
    },
    {
      no: '4.2',
      description: 'เดินท่อ/เดินสายไฟแสงสว่างใหม่ + กล่องพักสาย',
      unit: 'จุด',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- เดินท่อ PVC\n- เดินสายไฟใหม่ทั้งหมด\n- ติดตั้งกล่องพักสาย\n- TBD: รอแบบก่อสร้าง',
    },
    {
      no: '4.3',
      description: 'เดินปลั๊กกราวด์ใหม่ทั้งหมด (แยกวงจรตามโซน)',
      unit: 'จุด',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- ปลั๊ก 3 ขา มีกราวด์\n- แยกวงจรตามโซนใช้งาน\n- TBD: รอแบบก่อสร้าง',
    },
    {
      no: '4.4',
      description: 'วงจรเฉพาะ: แอร์ / เครื่องทำน้ำอุ่น / เตา-ฮูด / ไมโครเวฟ / ตู้เย็น / ซักผ้า',
      unit: 'วงจร',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- แยกวงจรสำหรับเครื่องใช้ไฟฟ้าขนาดใหญ่\n- ใช้สายขนาดเหมาะสม\n- TBD: รอแบบก่อสร้าง',
    },
    {
      no: '4.5',
      description: 'ใช้ตู้ Consumer Unit/MCB/RCD/RCBO เดิม',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- ใช้ตู้ไฟเดิม\n- ตรวจสอบและปรับปรุง\n- TBD: รอแบบก่อสร้าง',
    },
    {
      no: '4.6',
      description: 'ติดตั้งโคม/ดาวน์ไลท์/รางไฟ/ไฟซ่อน (ค่าแรง)',
      unit: 'จุด',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- ค่าแรงติดตั้งโคมไฟ\n- ดาวน์ไลท์\n- รางไฟและไฟซ่อน\n- TBD: รอแบบก่อสร้าง',
    },
    {
      no: '4.7',
      description: 'เดินระบบ LAN/TV/Internet/กล้อง',
      unit: 'จุด',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- เดินสาย LAN\n- จุดเชื่อมต่อ TV\n- Internet และกล้องวงจรปิด\n- TBD: รอแบบก่อสร้าง',
    },

    // 5) งานระบบประปา
    {
      no: '5',
      description: 'งานระบบประปา (Plumbing) "ท่อ PPR" — รอแบบก่อสร้าง (TBD)',
      unit: '-',
      quantity: '',
      unitPrice: '',
      laborCost: '',
    },
    {
      no: '5.1',
      description: 'รื้อท่อน้ำดี/น้ำทิ้งเดิมตามแนวทำใหม่',
      unit: 'งาน',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- รื้อท่อน้ำเดิม\n- เฉพาะแนวที่ต้องเปลี่ยนใหม่\n- TBD: รอแบบก่อสร้าง',
    },
    {
      no: '5.2',
      description: 'เดินท่อน้ำดี PPR ใหม่ (ห้องน้ำทั้งหมด)',
      unit: 'จุด',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- ท่อ PPR คุณภาพดี\n- เดินท่อน้ำดีทั้งระบบ\n- TBD: รอแบบก่อสร้าง',
    },
    {
      no: '5.3',
      description: 'เดินท่อน้ำทิ้ง PVC ใหม่ + ดักกลิ่น + slope',
      unit: 'จุด',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- ท่อ PVC น้ำทิ้ง\n- ติดตั้งดักกลิ่น\n- ปรับความลาดเอียงที่เหมาะสม\n- TBD: รอแบบก่อสร้าง',
    },
    {
      no: '5.4',
      description: 'เดินท่อระบายพื้นห้องน้ำ/กันย้อน',
      unit: 'จุด',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- ท่อระบายพื้น\n- ระบบกันน้ำย้อน\n- TBD: รอแบบก่อสร้าง',
    },
    {
      no: '5.5',
      description: 'วาล์วปิด-เปิดแยกโซน + ข้อต่อครบชุด',
      unit: 'ชุด',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- วาล์วปิด-เปิดน้ำแยกโซน\n- ข้อต่อครบชุด\n- TBD: รอแบบก่อสร้าง',
    },
    {
      no: '5.6',
      description: 'ทดสอบรั่วซึม/น้ำทิ้ง',
      unit: 'งาน',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- ทดสอบความรั่วซึม\n- ทดสอบระบบน้ำทิ้ง\n- TBD: รอแบบก่อสร้าง',
    },

    // 6) งานกันซึม + ห้องน้ำ
    {
      no: '6',
      description: 'งานกันซึม + ห้องน้ำ (Waterproof & Bathroom) — รอแบบก่อสร้าง (TBD)',
      unit: '-',
      quantity: '',
      unitPrice: '',
      laborCost: '',
    },
    {
      no: '6.1',
      description: 'กันซึมพื้น+ผนังห้องน้ำ',
      unit: 'ตร.ม.',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- ทากันซึมพื้น\n- ทากันซึมผนังสูง 1.80 ม.\n- TBD: รอแบบก่อสร้าง',
    },
    {
      no: '6.2',
      description: 'ปรับสโลประบายน้ำ/ทำพื้น Drop/ทำธรณี',
      unit: 'จุด',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- ปรับความลาดเอียงพื้น\n- ทำพื้น Drop zone\n- ทำธรณีดิน\n- TBD: รอแบบก่อสร้าง',
    },
    {
      no: '6.3',
      description: 'ปูกระเบื้องพื้นห้องน้ำใหม่ (ค่าแรง)',
      unit: 'ตร.ม.',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- ค่าแรงปูกระเบื้องพื้น\n- TBD: รอแบบก่อสร้าง',
    },
    {
      no: '6.4',
      description: 'ปูกระเบื้องผนังห้องน้ำใหม่ (ค่าแรง)',
      unit: 'ตร.ม.',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- ค่าแรงปูกระเบื้องผนัง\n- TBD: รอแบบก่อสร้าง',
    },
    {
      no: '6.5',
      description: 'ยาแนว/ซิลิโคน/เก็บรอยต่อ (ค่าแรง)',
      unit: 'งาน',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- ยาแนวกระเบื้อง\n- ซิลิโคนตามรอยต่อ\n- TBD: รอแบบก่อสร้าง',
    },
    {
      no: '6.6',
      description: 'ติดตั้งสุขภัณฑ์ใหม่ (ค่าแรง)',
      unit: 'ชุด',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- ค่าแรงติดตั้งสุขภัณฑ์\n- TBD: รอแบบก่อสร้าง',
    },
    {
      no: '6.7',
      description: 'ติดตั้งฉากกั้นอาบน้ำ/กระจก (ค่าแรง)',
      unit: 'ชุด',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- ค่าแรงติดตั้งฉากกั้น\n- กระจกกันน้ำ\n- TBD: รอแบบก่อสร้าง',
    },

    // 7) งานฝ้าเพดาน
    {
      no: '7',
      description: 'งานฝ้าเพดาน (Ceiling) "ทำใหม่" — รอแบบก่อสร้าง (TBD)',
      unit: '-',
      quantity: '',
      unitPrice: '',
      laborCost: '',
    },
    {
      no: '7.1',
      description: 'ฝ้ายิปซั่มทึบ + โครงคร่าวใหม่ทั้งห้อง',
      unit: 'ตร.ม.',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- โครงเหล็กฝ้า\n- ยิปซั่มบอร์ดทึบ\n- ทำใหม่ทั้งหมด\n- TBD: รอแบบก่อสร้าง',
    },
    {
      no: '7.2',
      description: 'ฝ้าหลุม/ฝ้าซ่อนไฟ/ทำช่องเซอร์วิส',
      unit: 'จุด',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- ฝ้าหลุมสำหรับไฟ\n- ช่องซ่อนไฟ\n- ช่องเซอร์วิสบำรุงรักษา\n- TBD: รอแบบก่อสร้าง',
    },
    {
      no: '7.3',
      description: 'ฉาบรอยต่อ/โป๊ว/ขัด/รองพื้นฝ้า',
      unit: 'ตร.ม.',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- ฉาบรอยต่อยิปซั่ม\n- โป๊วและขัดให้เรียบ\n- รองพื้นก่อนทาสี\n- TBD: รอแบบก่อสร้าง',
    },
    {
      no: '7.4',
      description: 'ทาสีฝ้า (ค่าแรง)',
      unit: 'ตร.ม.',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- ค่าแรงทาสีฝ้า\n- TBD: รอแบบก่อสร้าง',
    },

    // 8) งานพื้น
    {
      no: '8',
      description: 'งานพื้น (Flooring) "SPC ลายไม้" — รอแบบก่อสร้าง (TBD)',
      unit: '-',
      quantity: '',
      unitPrice: '',
      laborCost: '',
    },
    {
      no: '8.1',
      description: 'รื้อพื้นเดิม',
      unit: 'รายการ',
      quantity: '',
      unitPrice: '',
      laborCost: '',
      scopeDetails: 'Included ในหมวด 2.0',
    },
    {
      no: '8.2',
      description: 'ปรับระดับพื้น (self-leveling/screed เฉพาะจุด)',
      unit: 'ตร.ม.',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- ปรับระดับพื้น\n- self-leveling compound\n- screed เฉพาะจุดที่ไม่เรียบ\n- TBD: รอแบบก่อสร้าง',
    },
    {
      no: '8.3',
      description: 'ปูพื้น SPC (ค่าแรง)',
      unit: 'ตร.ม.',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- ค่าแรงปูพื้น SPC\n- ลายไม้\n- TBD: รอแบบก่อสร้าง',
    },
    {
      no: '8.4',
      description: 'ติดตั้งบัวพื้น/จบขอบ/โปรไฟล์รอยต่อ',
      unit: 'ม.',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- บัวพื้น\n- จบขอบประตู\n- โปรไฟล์รอยต่อ\n- TBD: รอแบบก่อสร้าง',
    },
    {
      no: '8.5',
      description: 'เก็บรอยต่อซิลิโคน/จบงาน',
      unit: 'งาน',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- ซิลิโคนรอยต่อ\n- เก็บรายละเอียด\n- TBD: รอแบบก่อสร้าง',
    },

    // 9) งานบิ้วอิน
    {
      no: '9',
      description: 'งานบิ้วอิน (Built-in) — รอแบบก่อสร้าง (TBD)',
      unit: '-',
      quantity: '',
      unitPrice: '',
      laborCost: '',
    },
    {
      no: '9.1',
      description: 'ติดตั้งท็อป/ซิงก์/ก๊อก (ค่าแรง)',
      unit: 'ชุด',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- ค่าแรงติดตั้งท็อป\n- ซิงก์และก๊อกน้ำ\n- TBD: รอแบบก่อสร้าง',
    },
    {
      no: '9.3',
      description: 'ตู้เสื้อผ้า/ตู้เก็บของ/ชั้นวาง/ผนังทีวี/ตู้รองเท้า (BF-01 …)',
      unit: 'ชุด',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- ตู้บิ้วอินตามแบบ\n- ตู้เสื้อผ้า\n- ตู้เก็บของ\n- ชั้นวางและผนังทีวี\n- ตู้รองเท้า\n- TBD: รอแบบก่อสร้าง',
    },
    {
      no: '9.4',
      description: 'งานบาน/รางลิ้นชัก/soft-close',
      unit: 'ชุด',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- บานตู้\n- รางลิ้นชัก soft-close\n- บานพับ\n- TBD: รอแบบก่อสร้าง',
    },
    {
      no: '9.5',
      description: 'เก็บสี/เก็บผิว/ซิลิโคน/จบงานบิ้วอิน',
      unit: 'งาน',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- เก็บสีและผิวบิ้วอิน\n- ซิลิโคนรอยต่อ\n- จบงานละเอียด\n- TBD: รอแบบก่อสร้าง',
    },

    // 10) งานสี
    {
      no: '10',
      description: 'งานสี (Painting) — รอแบบก่อสร้าง (TBD)',
      unit: '-',
      quantity: '',
      unitPrice: '',
      laborCost: '',
    },
    {
      no: '10.1',
      description: 'รองพื้นผนัง/โป๊ว/ขัด (รวมรอยซ่อม)',
      unit: 'ตร.ม.',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- รองพื้นผนัง\n- โป๊วรอยแตกร้าว\n- ขัดให้เรียบ\n- TBD: รอแบบก่อสร้าง',
    },
    {
      no: '10.2',
      description: 'ทาสีผนังภายใน (ค่าแรง)',
      unit: 'ตร.ม.',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- ค่าแรงทาสีผนัง\n- TBD: รอแบบก่อสร้าง',
    },
    {
      no: '10.4',
      description: 'ทาสีวงกบ/บัว/งานไม้ที่เกี่ยวข้อง (ค่าแรง)',
      unit: 'ม.',
      quantity: 0,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- ค่าแรงทาสีวงกบ\n- บัวพื้น\n- งานไม้อื่นๆ\n- TBD: รอแบบก่อสร้าง',
    },

    // 11) งานเก็บรายละเอียด/ส่งมอบ
    {
      no: '11',
      description: 'งานเก็บรายละเอียด/ส่งมอบ — รอแบบก่อสร้าง (TBD)',
      unit: '-',
      quantity: '',
      unitPrice: '',
      laborCost: '',
    },
    {
      no: '11.1',
      description: 'ทำความสะอาดใหญ่ก่อนส่งมอบ',
      unit: 'งาน',
      quantity: '',
      unitPrice: '',
      laborCost: '',
      scopeDetails: '- ทำความสะอาดทั้งหมด\\n- เช็ดกระจก\\n- ถูพื้น\\n- ดูดฝุ่น\\n\\n⚠️ TBD: รอแบบก่อสร้าง (Phase 1: งานรื้อ)',
    },
    {
      no: '11.2',
      description: 'เก็บ defect รอบแรก/รอบสอง',
      unit: 'งาน',
      quantity: '',
      unitPrice: '',
      laborCost: '',
      scopeDetails: '- ตรวจสอบและแก้ไขข้อบกพร่อง\\n- รอบแรกและรอบสอง\\n- จนกว่าจะเรียบร้อย\\n\\n⚠️ TBD: รอแบบก่อสร้าง (Phase 1: งานรื้อ)',
    },
    {
      no: '11.3',
      description: 'ส่งมอบงาน + checklist + รูป as-built',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 0,
      scopeDetails: '- ส่งมอบงานเรียบร้อย\n- checklist ตรวจสอบ\n- รูปถ่าย as-built\n- เอกสารรับประกัน',
    },
  ],
};
