import { ProjectData } from './projectData';

export const villaRatchathewi175: ProjectData = {
  id: 'villa-ratchathewi-room175',
  name: 'VILLA Ratchathewi (2BR ROOM 175)',
  address: 'คอนโด VILLA Ratchathewi, ห้อง 175 (2 ห้องนอน)',
  phone: '-',
  owner: '-',
  quotationData: [
    // A) ค่าออกแบบ
    {
      no: 'A',
      description: 'ค่าออกแบบ / แบบก่อสร้าง',
      unit: '',
      quantity: '',
      unitPrice: '',
      laborCost: '',
    },
    {
      no: 'A.1',
      description: 'ออกแบบ + แบบก่อสร้าง',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 30000,
      laborCost: 0,
      scopeDetails: '• ออกแบบรีโนเวทคอนโด 2 ห้องนอน (175 ตร.ม.)\n• จัดทำแบบก่อสร้างครบชุด\n• แบบ Layout, แบบไฟฟ้า, แบบประปา\n• แบบ 3D Perspective\n• Final Design (ราคาลูกค้าสุดท้าย ไม่บวกกำไร)',
    },

    // B) รื้อถอน (รวมค่าขนทิ้ง)
    {
      no: 'B',
      description: 'รื้อถอน (Demolition) - รวมค่าขนทิ้ง',
      unit: '',
      quantity: '',
      unitPrice: '',
      laborCost: '',
    },
    {
      no: 'B.1',
      description: 'เหมาทั้งหมด (รื้อบิ้วอิน/ผนัง/ฝ้า/พื้น/ห้องน้ำ/ระบบเดิม)',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 55000,
      scopeDetails: '• รื้อบิ้วอินทั้งหมด + ขนลง\n• ทุบผนังตามแบบ + ขนทิ้ง\n• รื้อฝ้าเก่าทั้งหมด + ขนทิ้ง\n• รื้อพื้นเดิมทั้งหมด + ขนทิ้ง\n• รื้อชุดครัวเดิม/ซิงค์/ท่อน้ำทิ้งเดิม\n• รื้อสุขภัณฑ์เดิม/ฉากกั้น/อุปกรณ์ห้องน้ำเดิม\n• สกัดกระเบื้องพื้น+ผนังห้องน้ำทั้งหมด\n• รื้อระบบไฟฟ้า/ประปาเดิมตามจุดที่เปลี่ยนใหม่\n• ขนทิ้งเศษวัสดุออกจากพื้นที่\n\n*** ราคาเหมาครอบคลุมทั้งหมด ***',
    },

    // C) ก่อฉาบอิฐมวลเบา
    {
      no: 'C',
      description: 'ก่อฉาบอิฐมวลเบา (Lightweight Block Masonry)',
      unit: '',
      quantity: '',
      unitPrice: '',
      laborCost: '',
      scopeDetails: '• งานก่อผนังอิฐมวลเบา 20 ตร.ม.',
    },
    {
      no: 'C.1',
      description: 'อิฐมวลเบา 7.5–10 ซม.',
      unit: 'ตร.ม.',
      quantity: 20,
      unitPrice: 180,
      laborCost: 0,
      scopeDetails: '• อิฐมวลเบาคุณภาพดี ขนาด 7.5-10 ซม.\n• น้ำหนักเบา แข็งแรง\n• เหมาะกับงานรีโนเวทคอนโด',
    },
    {
      no: 'C.2',
      description: 'ปูนก่อ/ฉาบ/ทราย',
      unit: 'เหมา',
      quantity: 1,
      unitPrice: 2400,
      laborCost: 0,
      scopeDetails: '• ปูนก่อคุณภาพดี\n• ปูนฉาบเรียบ\n• ทรายหยาบและทรายละเอียด',
    },
    {
      no: 'C.3',
      description: 'ค่าแรงก่อ–ฉาบ',
      unit: 'ตร.ม.',
      quantity: 20,
      unitPrice: 0,
      laborCost: 700,
      scopeDetails: '• ค่าแรงก่อผนัง\n• ฉาบเรียบ 2 ด้าน\n• เก็บมุม 90 องศา\n• เตรียมผิวก่อนทาสี',
    },

    // D) งานไฟฟ้า (เดินใหม่ทั้งห้อง)
    {
      no: 'D',
      description: 'งานไฟฟ้า (Electrical System) - เดินใหม่ทั้งห้อง',
      unit: '',
      quantity: '',
      unitPrice: '',
      laborCost: '',
      scopeDetails: '• Scope: เดินในผนัง + เดินบนฝ้า\n• สายไฟ Phelps Dodge\n• Downlight 17 ดวง\n• Tracklight 6 ม. × 2 เส้น + 8 โคม + 8 หลอด\n• Strip LED ตามรายการ (ยาวรวม ~22 เมตร)\n• Driver 6-7 ตัว (แยก zone)',
    },
    {
      no: 'D.1',
      description: 'จุดไฟ/ปลั๊ก/สวิตช์ (เฉลี่ย 45 จุด)',
      unit: 'จุด',
      quantity: 45,
      unitPrice: 0,
      laborCost: 750,
      scopeDetails: '• เดินสายไฟ THW 1.5/2.5 ร้อยท่อ uPVC\n• ติดตั้งสวิตช์และปลั๊ก\n• หน้ากาก Panasonic/Schneider\n• ทดสอบระบบ',
    },
    {
      no: 'D.2',
      description: 'วงจรหนัก (แอร์/เตา/น้ำอุ่น ฯลฯ)',
      unit: 'จุด',
      quantity: 7,
      unitPrice: 0,
      laborCost: 3000,
      scopeDetails: '• วงจรเฉพาะแอร์ (2-3 เครื่อง)\n• วงจรเครื่องทำน้ำอุ่น\n• วงจรเตา-ฮูด\n• วงจรไมโครเวฟ/ตู้เย็น\n• ใช้สาย THW 4/6 ตร.มม.\n• เบรกเกอร์แยกวงจร',
    },
    {
      no: 'D.3',
      description: 'สายไฟ THW 1.5/2.5/4/6',
      unit: 'เหมา',
      quantity: 1,
      unitPrice: 18000,
      laborCost: 0,
      scopeDetails: '• สายไฟ Phelps Dodge คุณภาพดี\n• THW 1.5 ตร.มม. (ไฟสว่าง)\n• THW 2.5 ตร.มม. (ปลั๊ก)\n• THW 4/6 ตร.มม. (วงจรหนัก)\n• ครบตามจุดใช้งาน',
    },
    {
      no: 'D.4',
      description: 'ท่อไฟ/อุปกรณ์',
      unit: 'เหมา',
      quantity: 1,
      unitPrice: 9500,
      laborCost: 0,
      scopeDetails: '• ท่อ uPVC ร้อยสาย\n• กล่องพักสาย\n• ข้อต่อ/ข้องอ\n• เทปพันสายไฟ\n• อุปกรณ์ประกอบอื่นๆ',
    },
    {
      no: 'D.5',
      description: 'ติดตั้ง Downlight',
      unit: 'ดวง',
      quantity: 17,
      unitPrice: 0,
      laborCost: 200,
      scopeDetails: '• ค่าแรงติดตั้ง Downlight\n• เจาะรูบนฝ้า\n• เดินสายและต่อไดร์เวอร์\n• ทดสอบแสงสว่าง',
    },
    {
      no: 'D.6',
      description: 'Tracklight (ติดโคม+ต่อไดร์เวอร์)',
      unit: 'โคม',
      quantity: 16,
      unitPrice: 0,
      laborCost: 250,
      scopeDetails: '• ติดตั้งรางไฟ Tracklight 6 ม. × 2 เส้น\n• ติดโคม 8 ดวง\n• ติดตั้งหลอด 8 หลอด\n• ต่อไดร์เวอร์\n• ทดสอบระบบ',
    },
    {
      no: 'D.7',
      description: 'Strip Light (กัดร่อง/ซ่อน) - รวมยาว ~22 เมตร',
      unit: 'เมตร',
      quantity: 22,
      unitPrice: 0,
      laborCost: 650,
      scopeDetails: '• กัดร่องบนผนัง/ฝ้า\n• ยิง profile อลูมิเนียม\n• เดินสาย Strip LED\n• ซ่อนสายและไดร์เวอร์\n• ปิดฝาครบ\n• ทดสอบแสง',
    },
    {
      no: 'D.8',
      description: 'ค่าติดตั้ง Driver (6–7 ตัว zone)',
      unit: 'ตัว',
      quantity: 7,
      unitPrice: 0,
      laborCost: 800,
      scopeDetails: '• ติดตั้ง Driver แยก zone\n• ซ่อนในตำแหน่งที่เหมาะสม\n• ต่อสายครบถ้วน\n• ทดสอบทุก zone',
    },
    {
      no: 'D.9',
      description: 'ทดสอบ/ยิง Label วงจร',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 4000,
      scopeDetails: '• ทดสอบระบบไฟฟ้าทั้งหมด\n• วัดค่าแรงดัน/กระแส\n• ยิง Label ระบุวงจรที่ตู้เบรกเกอร์\n• ทำเอกสาร As-Built',
    },

    // E) ระบบประปา PPR (ห้องน้ำเดียว)
    {
      no: 'E',
      description: 'ระบบประปา PPR (Plumbing System)',
      unit: '',
      quantity: '',
      unitPrice: '',
      laborCost: '',
      scopeDetails: '• งานประปาห้องน้ำเดียว\n• ท่อ PPR คุณภาพดี\n• ครบ 7 จุด',
    },
    {
      no: 'E.1',
      description: 'จุดน้ำดี PPR',
      unit: 'จุด',
      quantity: 7,
      unitPrice: 0,
      laborCost: 2600,
      scopeDetails: '• เดินท่อ PPR น้ำดี\n• จุดอ่างล้างหน้า\n• จุดชักโครก\n• จุดฝักบัว\n• จุดน้ำอุ่น\n• จุดอื่นๆ ตามแบบ\n• รวมข้อต่อและอุปกรณ์',
    },
    {
      no: 'E.2',
      description: 'ท่อทิ้ง PVC/ดักกลิ่น/สโลป',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 5000,
      scopeDetails: '• เดินท่อ PVC น้ำทิ้ง\n• ติดตั้งดักกลิ่น\n• ปรับความลาดเอียง (slope)\n• ท่อระบายพื้น',
    },
    {
      no: 'E.3',
      description: 'Valve/ข้อต่อ/ข้องอ 90°',
      unit: 'เหมา',
      quantity: 1,
      unitPrice: 2800,
      laborCost: 0,
      scopeDetails: '• วาล์วปิด-เปิดน้ำ\n• ข้อต่อ PPR\n• ข้องอ 90 องศา\n• อุปกรณ์ประกอบอื่นๆ',
    },
    {
      no: 'E.4',
      description: 'ทดสอบแรงดัน',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 2000,
      scopeDetails: '• ทดสอบแรงดันน้ำ\n• ตรวจสอบรั่วซึม\n• รับประกันคุณภาพ',
    },

    // F) ห้องน้ำ (ห้องเดียว)
    {
      no: 'F',
      description: 'ห้องน้ำ (Bathroom) - ห้องเดียว',
      unit: '',
      quantity: '',
      unitPrice: '',
      laborCost: '',
      scopeDetails: '• งานห้องน้ำครบวงจร\n• กันซึม Dr. Fixit 2K (3 Coat)\n• กระเบื้อง 60×120\n• สุขภัณฑ์ครบชุด',
    },
    {
      no: 'F.1',
      description: 'กันซึม Dr. Fixit 2K (3 Coat) - พื้นที่ ~10 ตร.ม.',
      unit: 'ตร.ม.',
      quantity: 10,
      unitPrice: 0,
      laborCost: 750,
      scopeDetails: '• กันซึม Dr. Fixit 2K\n• ทาครบ 3 Coat\n• พื้น + ผนังสูง 1.80 ม.\n• มาตรฐานการก่อสร้าง',
    },
    {
      no: 'F.2',
      description: 'ปรับ slope',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 4000,
      scopeDetails: '• ปรับความลาดเอียงพื้น\n• ระบายน้ำดี\n• ไม่เกิดน้ำขัง',
    },
    {
      no: 'F.3',
      description: 'ปูกระเบื้องพื้น 60×120 (ค่าแรง 10 ตร.ม.)',
      unit: 'ตร.ม.',
      quantity: 10,
      unitPrice: 0,
      laborCost: 700,
      scopeDetails: '• ค่าแรงปูกระเบื้องพื้น\n• ขนาด 60×120 ซม.\n• ปูนกาวคุณภาพดี\n• เก็บระดับเรียบ',
    },
    {
      no: 'F.4',
      description: 'ปูกระเบื้องผนัง 60×120 (ค่าแรง ~26 ตร.ม.)',
      unit: 'ตร.ม.',
      quantity: 26,
      unitPrice: 0,
      laborCost: 750,
      scopeDetails: '• ค่าแรงปูกระเบื้องผนัง\n• ขนาด 60×120 ซม.\n• สูงประมาณ 2.40 ม.\n• เก็บมุม 90 องศา',
    },
    {
      no: 'F.5',
      description: 'ยาแนว/ซิลิโคน',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 4000,
      scopeDetails: '• ยาแนวกระเบื้อง\n• ซิลิโคนกันน้ำตามรอยต่อ\n• เก็บผิวเรียบสวยงาม',
    },
    {
      no: 'F.6',
      description: 'ติดตั้งสุขภัณฑ์ 1 ห้อง',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 6000,
      scopeDetails: '• ติดตั้งอ่างล้างหน้า + ก๊อก\n• ติดตั้งชักโครก\n• ติดตั้งฝักบัว + เซ็ต\n• ติดตั้งเครื่องทำน้ำอุ่น\n• อุปกรณ์ห้องน้ำเสริม',
    },
    {
      no: 'F.7',
      description: 'ติดตั้งฉากกั้น',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: 0,
      laborCost: 3500,
      scopeDetails: '• ฉากกั้นอาบน้ำ\n• กระจกกันน้ำ\n• บานพับสแตนเลส\n• มือจับและล็อค',
    },
    {
      no: 'F.8',
      description: 'ปูกระเบื้องระเบียง 10 ตร.ม.',
      unit: 'ตร.ม.',
      quantity: 10,
      unitPrice: 0,
      laborCost: 550,
      scopeDetails: '• ค่าแรงปูกระเบื้องระเบียง\n• พื้นที่ 10 ตร.ม.\n• กระเบื้องกันลื่น',
    },

    // G) งานฝ้า
    {
      no: 'G',
      description: 'งานฝ้า (Ceiling)',
      unit: '',
      quantity: '',
      unitPrice: '',
      laborCost: '',
      scopeDetails: '• ฝ้ายิปซั่มทึบ\n• โครงเหล็กอย่างดี\n• พื้นที่รวม ~77 ตร.ม.',
    },
    {
      no: 'G.1',
      description: 'ฝ้าหลุมนั่งเล่น 40.6 ตร.ม.',
      unit: 'ตร.ม.',
      quantity: 40.6,
      unitPrice: 0,
      laborCost: 800,
      scopeDetails: '• โครงเหล็กฝ้า C-Stud\n• ยิปซั่มบอร์ดทึบ 9 มม.\n• ฝ้าหลุมตามแบบ\n• ช่องสำหรับ Downlight/Tracklight\n• ฉาบรอยต่อ\n• รองพื้นก่อนทาสี',
    },
    {
      no: 'G.2',
      description: 'ฝ้าห้องนอน 26.43 ตร.ม.',
      unit: 'ตร.ม.',
      quantity: 26.43,
      unitPrice: 0,
      laborCost: 600,
      scopeDetails: '• โครงเหล็กฝ้า C-Stud\n• ยิปซั่มบอร์ดทึบ 9 มม.\n• ฝ้าเรียบ\n• ฉาบรอยต่อ\n• รองพื้นก่อนทาสี',
    },
    {
      no: 'G.3',
      description: 'ฝ้าห้องน้ำกันชื้น 10 ตร.ม.',
      unit: 'ตร.ม.',
      quantity: 10,
      unitPrice: 0,
      laborCost: 650,
      scopeDetails: '• โครงเหล็กฝ้ากันสนิม\n• บอร์ดกันชื้น (Smartboard/Fiber Cement)\n• เหมาะกับห้องน้ำ\n• ฉาบรอยต่อกันน้ำ\n• รองพื้นก่อนทาสี',
    },

    // H) พื้น SPC (ค่าแรง)
    {
      no: 'H',
      description: 'พื้น SPC (SPC Flooring) - ค่าแรง',
      unit: '',
      quantity: '',
      unitPrice: '',
      laborCost: '',
      scopeDetails: '• พื้น SPC ลายไม้\n• พื้นที่ 64 ตร.ม.\n• กันน้ำ 100%\n• ทนทาน',
    },
    {
      no: 'H.1',
      description: 'ปู SPC 64 ตร.ม.',
      unit: 'ตร.ม.',
      quantity: 64,
      unitPrice: 0,
      laborCost: 250,
      scopeDetails: '• ค่าแรงปูพื้น SPC\n• ปรับระดับพื้นเบื้องต้น\n• ปูแนบสนิท ไม่มีช่องว่าง\n• เก็บรอยต่อเรียบ',
    },
    {
      no: 'H.2',
      description: 'บัว/จบขอบ',
      unit: 'เมตร',
      quantity: 45,
      unitPrice: 0,
      laborCost: 50,
      scopeDetails: '• ติดตั้งบัวพื้น PVC\n• จบขอบประตู\n• โปรไฟล์รอยต่อ\n• เก็บงานเรียบร้อย',
    },

    // I) สีผนัง
    {
      no: 'I',
      description: 'สีผนัง (Painting)',
      unit: '',
      quantity: '',
      unitPrice: '',
      laborCost: '',
      scopeDetails: '• ทาสีผนังทั้งห้อง\n• พื้นที่ ~200 ตร.ม.\n• สีคุณภาพดี',
    },
    {
      no: 'I.1',
      description: 'รองพื้น + ซ่อมผิว',
      unit: 'ตร.ม.',
      quantity: 200,
      unitPrice: 0,
      laborCost: 60,
      scopeDetails: '• รองพื้นผนัง\n• โป๊วรอยแตกร้าว\n• อุดรอยบกพร่อง\n• ขัดให้เรียบ',
    },
    {
      no: 'I.2',
      description: 'ทาสี 2–3 รอบ',
      unit: 'ตร.ม.',
      quantity: 200,
      unitPrice: 0,
      laborCost: 70,
      scopeDetails: '• ทาสีผนังภายใน\n• สี TOA/Beger คุณภาพดี\n• ทา 2-3 รอบ หรือจนปกปิด\n• เก็บผิวเรียบสวย',
    },

    // J) เก็บงาน / Defect / Big Cleaning
    {
      no: 'J',
      description: 'เก็บงาน / Defect / Big Cleaning',
      unit: '',
      quantity: '',
      unitPrice: '',
      laborCost: '',
      scopeDetails: '• เก็บงานละเอียด\n• แก้ไขข้อบกพร่อง\n• ทำความสะอาดส่งมอบ',
    },
    {
      no: 'J.1',
      description: 'Big Cleaning',
      unit: 'งาน',
      quantity: 1,
      unitPrice: 0,
      laborCost: 8000,
      scopeDetails: '• ทำความสะอาดใหญ่ทั้งห้อง\n• ดูดฝุ่น ถูพื้น\n• เช็ดกระจก/ผนัง/เฟอร์\n• เก็บเศษวัสดุละเอียด',
    },
    {
      no: 'J.2',
      description: 'Defect 2 รอบ',
      unit: 'รอบ',
      quantity: 2,
      unitPrice: 0,
      laborCost: 3000,
      scopeDetails: '• ตรวจสอบข้อบกพร่อง\n• แก้ไขจุดที่ต้องปรับปรุง\n• รอบที่ 1: หลังเสร็จงานหลัก\n• รอบที่ 2: ก่อนส่งมอบ',
    },

    // ===== BUILT-IN =====
    // K) Living Room
    {
      no: 'K',
      description: 'หมวด Built-in: ห้องนั่งเล่น (Living Room)',
      unit: '',
      quantity: '',
      unitPrice: '',
      laborCost: '',
      scopeDetails: '• Stone veneer wall 15.3 ตร.ม.\n• ชุดทีวี 3.65×2.20×0.40\n• ตู้โชว์โต๊ะทานข้าว 2.40×2.80×0.35\n• เคาน์เตอร์บาร์ 2.35×0.60×0.80\n• ตู้เก็บของ+ตู้รองเท้า 2.00×2.50×0.35',
    },
    {
      no: 'K.1',
      description: 'Stone veneer wall 15.3 ตร.ม.',
      unit: 'ตร.ม.',
      quantity: 15.3,
      unitPrice: 0,
      laborCost: 1500,
      scopeDetails: '• ผนังหินปูนอัดสำเร็จรูป (Stone veneer)\n• ค่าแรงติดตั้ง + ปูนกาว\n• เก็บขอบและรอยต่อ\n• ทำความสะอาดผิวหิน',
    },
    {
      no: 'K.2',
      description: 'ชุดทีวี 3.65 × สูง 2.20 × ลึก 0.40',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: 50000,
      laborCost: 0,
      scopeDetails: '• โครง HMR กันชื้น\n• ลามิเนตสองด้าน\n• ช่องโชว์ตกแต่ง\n• ชุดหน้าบาน Soft-close\n• ช่องสำหรับทีวี + อุปกรณ์\n• ซ่อนสายไฟเรียบร้อย',
    },
    {
      no: 'K.3',
      description: 'ตู้โชว์โต๊ะทานข้าว 2.40 × สูง 2.80 × ลึก 0.35',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: 67500,
      laborCost: 0,
      scopeDetails: '• ตู้สูง 2.80 ม. มีโครงรับแข็งแรง\n• บานเต็มทั้งตู้ Soft-close\n• ชั้นวางปรับระดับได้\n• กระจกโชว์ตกแต่ง\n• ไฟ LED ภายในตู้\n• ลามิเนตเกรดดี',
    },
    {
      no: 'K.4',
      description: 'เคาน์เตอร์บาร์ 2.35 × 0.60 × 0.80',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: 34000,
      laborCost: 0,
      scopeDetails: '• โครง HMR แข็งแรง\n• ความสูง 0.80 ม. เหมาะนั่งสบาย\n• มีที่เก็บของใต้เคาน์เตอร์\n• เตรียมช่องเดินไฟ\n• ลามิเนต/ทาสีตามแบบ',
    },
    {
      no: 'K.5',
      description: 'ตู้เก็บของ + ตู้รองเท้า 2.00 × สูง 2.50 × ลึก 0.35',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: 47500,
      laborCost: 0,
      scopeDetails: '• ตู้เก็บของอเนกประสงค์\n• ส่วนล่าง: ตู้รองเท้า\n• ส่วนบน: เก็บของใช้ทั่วไป\n• บาน Soft-close ทั้งหมด\n• ชั้นวางปรับระดับได้\n• ลามิเนตเกรดดี',
    },

    // L) Kitchen
    {
      no: 'L',
      description: 'หมวด Built-in: ครัว (Kitchen)',
      unit: '',
      quantity: '',
      unitPrice: '',
      laborCost: '',
      scopeDetails: '• ตู้ลอย 2.40×1.00×0.35\n• ตู้เตี้ย 1.50×0.80×0.60\n• *** หมายเหตุ: Top หินสังเคราะห์ลูกค้าจัดหาเอง ***',
    },
    {
      no: 'L.1',
      description: 'ตู้ลอย 2.40 × สูง 1.00 × ลึก 0.35',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: 40000,
      laborCost: 0,
      scopeDetails: '• ตู้แขวนบนครัว\n• โครง HMR กันชื้น\n• บานเปิด Soft-close\n• ชั้นวางปรับระดับได้\n• ลามิเนต/ทาสีตามแบบ\n• ยึดผนังแข็งแรง',
    },
    {
      no: 'L.2',
      description: 'ตู้เตี้ย 1.50 × สูง 0.80 × ลึก 0.60',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: 34000,
      laborCost: 0,
      scopeDetails: '• ตู้ล่างครัว\n• โครง HMR กันชื้นและความร้อน\n• รองรับ Sink + เตา\n• บานเปิด/ลิ้นชัก Soft-close\n• เตรียมช่องสำหรับท่อน้ำและไฟ\n• ไม่รวม Top หินสังเคราะห์ (ลูกค้าจัดหาเอง)',
    },

    // M) Master Bedroom
    {
      no: 'M',
      description: 'หมวด Built-in: ห้องนอนใหญ่ (Master Bedroom)',
      unit: '',
      quantity: '',
      unitPrice: '',
      laborCost: '',
      scopeDetails: '• บิ้วผนังตกแต่ง 21.40 ตร.ม.\n• ฐานเตียงติดกระจก 2.50×0.50×0.45\n• ตู้โชว์ 2.40×0.80×0.35\n• โต๊ะเครื่องแป้ง 1.65×0.40×0.15\n• ตู้เสื้อผ้า 1: 3.60×0.60×2.40\n• ตู้เสื้อผ้า 2: 2.20×0.60×2.40',
    },
    {
      no: 'M.1',
      description: 'บิ้วผนังตกแต่ง 21.40 ตร.ม.',
      unit: 'ตร.ม.',
      quantity: 21.4,
      unitPrice: 0,
      laborCost: 2500,
      scopeDetails: '• ผนังตกแต่งหลังเตียง/ผนังเน้น\n• ลามิเนตเต็มผิวตามแบบ\n• โครงไม้/โครงเหล็ก\n• ซ่อนไฟ LED ตามร่อง\n• เก็บผิวเรียบสวยงาม\n• ครบพื้นที่ 21.40 ตร.ม.',
    },
    {
      no: 'M.2',
      description: 'ฐานเตียงติดกระจก Debed 2.50 × 0.50 × 0.45',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: 20000,
      laborCost: 0,
      scopeDetails: '• ฐานเตียงบิ้วอิน\n• โครง HMR แข็งแรง\n• กระจกตกแต่งด้านหน้า (Debed style)\n• ความสูง 0.45 ม. นั่งสบาย\n• ที่เก็บของใต้เตียง\n• ลามิเนต/ทาสีตามแบบ',
    },
    {
      no: 'M.3',
      description: 'ตู้โชว์ 2.40 × 0.80 × 0.35',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: 24000,
      laborCost: 0,
      scopeDetails: '• ตู้โชว์ติดผนัง\n• บานกระจก/บานทึบ Soft-close\n• ชั้นวางปรับระดับได้\n• ไฟ LED ภายในตู้\n• ลามิเนตเกรดดี',
    },
    {
      no: 'M.4',
      description: 'โต๊ะเครื่องแป้ง 1.65 × 0.40 × 0.15 + Top หินสังเคราะห์',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: 18000,
      laborCost: 0,
      scopeDetails: '• โต๊ะเครื่องแป้งบิ้วอิน\n• โครง HMR\n• ลิ้นชัก Soft-close\n• ไม่รวมราคา Top หินสังเคราะห์ (ลูกค้าจัดหาเอง)\n• กระจกห้อยติดผนัง\n• ไฟ LED รอบกระจก',
    },
    {
      no: 'M.5',
      description: 'ตู้เสื้อผ้า 1: 3.60 × 0.60 × สูง 2.40',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: 102500,
      laborCost: 0,
      scopeDetails: '• ตู้เสื้อผ้าขนาดใหญ่\n• โครง HMR แข็งแรง\n• บานเปิด/บานเลื่อน Soft-close\n• ราวแขวนเสื้อสแตนเลส\n• ชั้นวางและลิ้นชักภายใน\n• กระจกบานเลื่อนตกแต่ง\n• ไฟ LED อัตโนมัติ\n• ลามิเนตเกรดดี',
    },
    {
      no: 'M.6',
      description: 'ตู้เสื้อผ้า 2: 2.20 × 0.60 × สูง 2.40',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: 70000,
      laborCost: 0,
      scopeDetails: '• ตู้เสื้อผ้าขนาดกลาง\n• โครง HMR แข็งแรง\n• บานเปิด Soft-close\n• ราวแขวนเสื้อสแตนเลส\n• ชั้นวางและลิ้นชักภายใน\n• ไฟ LED อัตโนมัติ\n• ลามิเนตเกรดดี',
    },

    // N) Bathroom Built-in
    {
      no: 'N',
      description: 'หมวด Built-in: ห้องน้ำ (Bathroom)',
      unit: '',
      quantity: '',
      unitPrice: '',
      laborCost: '',
      scopeDetails: '• เคาน์เตอร์อ่าง 0.50×0.95×0.50\n• ตู้ลอย 1.00×1.20×0.20\n• กระจกใหญ่ 0.90×1.50 + 1.00×0.35',
    },
    {
      no: 'N.1',
      description: 'เคาน์เตอร์อ่าง Top หิน 0.50 × 0.95 × สูง 0.50',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: 13500,
      laborCost: 0,
      scopeDetails: '• เคาน์เตอร์อ่างล้างหน้า\n• โครง HMR กันชื้น\n• บานเปิด/ลิ้นชัก Soft-close\n• ไม่รวมราคา Top หินสังเคราะห์ (ลูกค้าจัดหาเอง)\n• เตรียมช่องสำหรับท่อน้ำ\n• ลามิเนต/ทาสีกันชื้น',
    },
    {
      no: 'N.2',
      description: 'ตู้ลอย 1.00 × 1.20 × 0.20',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: 16000,
      laborCost: 0,
      scopeDetails: '• ตู้แขวนเก็บของห้องน้ำ\n• โครง HMR กันชื้นพิเศษ\n• บานเปิด Soft-close\n• ชั้นวางปรับระดับได้\n• ทาสีกันชื้น/ลามิเนต\n• ยึดผนังแข็งแรง',
    },
    {
      no: 'N.3',
      description: 'กระจกใหญ่ 0.90 × 1.50 + 1.00 × 0.35 (พร้อมเฟรม)',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: 13500,
      laborCost: 0,
      scopeDetails: '• กระจกเงาคุณภาพดี\n• เฟรมอลูมิเนียม/สแตนเลส\n• กระจกหลัก 0.90×1.50 ม.\n• กระจกเสริม 1.00×0.35 ม.\n• ติดตั้งแน่นหนา ปลอดภัย\n• ไฟ LED รอบกระจก (optional)',
    },

    // O) Bedroom 2
    {
      no: 'O',
      description: 'หมวด Built-in: ห้องนอน 2 (Bedroom 2)',
      unit: '',
      quantity: '',
      unitPrice: '',
      laborCost: '',
      scopeDetails: '• ตู้ลอย 1.60×0.95×0.30\n• ฐานเตียง 1.00×1.90\n• ผนังตกแต่ง 6.55 ตร.ม.',
    },
    {
      no: 'O.1',
      description: 'ตู้ลอย 1.60 × สูง 0.95 × ลึก 0.30',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: 20000,
      laborCost: 0,
      scopeDetails: '• ตู้แขวนติดผนัง\n• โครง HMR\n• บานเปิด Soft-close\n• ชั้นวางปรับระดับได้\n• ลามิเนต/ทาสีตามแบบ\n• ยึดผนังแข็งแรง',
    },
    {
      no: 'O.2',
      description: 'ฐานเตียง 1.00 × 1.90',
      unit: 'ชุด',
      quantity: 1,
      unitPrice: 13500,
      laborCost: 0,
      scopeDetails: '• ฐานเตียงบิ้วอิน\n• โครง HMR แข็งแรง\n• ความสูง 0.35-0.40 ม.\n• ที่เก็บของใต้เตียง\n• ลามิเนต/ทาสีตามแบบ',
    },
    {
      no: 'O.3',
      description: 'ผนังตกแต่ง 6.55 ตร.ม.',
      unit: 'ตร.ม.',
      quantity: 6.55,
      unitPrice: 0,
      laborCost: 3050,
      scopeDetails: '• ผนังตกแต่งหลังเตียง/ผนังเน้น\n• ลามิเนต/วอลเปเปอร์/ทาสีพิเศษ\n• โครงไม้/โครงเหล็ก\n• เก็บผิวเรียบสวยงาม\n• พื้นที่ 6.55 ตร.ม.',
    },
  ],
};
